const T = (term, meaning) => [term, meaning];

const PERIOD_TITLES = {
  25: "PR Target과 Fixture",
  26: "GitHub 인증과 최소 권한",
  27: "REST 상태 코드와 복구",
  28: "LangGraph State와 분기",
  29: "Checkpoint와 Idempotency",
  30: "Human Approval과 Interrupt",
  31: "Dry-run Comment Payload",
  32: "Sandbox GitHub 게시",
  33: "Meeting·Review Service Router",
  34: "LangSmith Trace 구조",
  35: "운영 Metadata와 Monitoring",
  36: "Dataset Experiment와 Release Gate",
  37: "Human Feedback과 Annotation",
  38: "PII·Retention·Incident 운영",
  39: "Release Candidate와 Vercel Demo",
  40: "최종 Demo와 Scorecard",
};

const P = (hour, title, config) => ({
  hour,
  title: PERIOD_TITLES[hour] ?? title,
  mode: "강의 12분 · 강사 시연 10분 · Codex 소프트웨어 제작 23분 · 실행 확인 5분",
  ...config,
  screenshot: hour === 22
    ? ["vscode-pytest-19-passed-local.png", config.screenshot[1]]
    : config.screenshot,
});

const DAY2_PERIODS_V2 = [
  P(9, "회의 Agent 전체 지도", {
    outcome: "LLM 호출·고정 Workflow·Agent 판단을 구분하고 상황에 맞는 제품 경계를 그린다.",
    why: "요약 한 번을 Agent라 부르면 비용·오류·승인 위치를 설명할 수 없다.",
    artifact: "01_architecture.json",
    terms: [T("LLM", "주어진 맥락으로 하나의 결과를 만드는 모델"), T("Workflow", "순서와 실패 규칙을 코드로 고정한 흐름"), T("Agent", "상황을 보고 다음 도구와 순서를 선택하는 시스템"), T("Human gate", "외부 쓰기 전 사람이 확정하는 경계")],
    pipeline: ["사용자 요청", "입력 유형 판단", "고정 처리", "필요한 사고만 LLM", "사람 확정"],
    files: ["src/course_services/day2_meeting_workflow.py", "materials/day2/일반인을_위한_회의기록_Agent_설계.md", "tests/test_day2_meeting_workflow.py", "materials/day2/day2_service_lab.ipynb"],
    command: "python -m pytest -q tests/test_day2_meeting_workflow.py",
    failure: "모든 단계를 상위 모델에게 맡겨 같은 입력에도 비용과 결과가 달라진다.",
    recovery: "입력 검사·STT·schema·증거 검증은 코드로 고정하고 요약·맥락 해석만 모델에게 맡긴다.",
    codex: "세 입력 시나리오와 외부 쓰기 금지를 명세하고 가장 작은 실행 구조를 제안받는다.",
    normalTest: "요청이 LLM·Workflow·Agent 중 어디에 속하는지 이유와 함께 반환된다.",
    boundaryTest: "자동 발송·게시 요청은 external_write=false와 APPROVAL_REQUIRED로 끝난다.",
    serviceCase: "비개발자도 한눈에 읽는 회의기록 제품 설계도",
    screenshot: ["day2-agent-architecture.png", "local:materials/day2/일반인을_위한_회의기록_Agent_설계.md"],
  }),
  P(10, "세 가지 입력과 STT 선택", {
    outcome: "Meet 전사·ClovaNote TXT·녹음 파일을 하나의 TranscriptEnvelope로 변환한다.",
    why: "이미 있는 텍스트를 다시 STT하면 느리고 화자 정보도 잃는다.",
    artifact: "02_inputs.json",
    terms: [T("Input adapter", "다른 형식을 공통 구조로 바꾸는 코드"), T("STT", "음성을 텍스트로 바꾸는 처리"), T("Source mode", "전사가 어디서 왔는지 남기는 필드"), T("Provenance", "출처·시각·변환 이력")],
    pipeline: ["입력 선택", "파서 또는 STT", "화자·시각 보존", "출처 기록", "공통 계약 검증"],
    files: ["data/day2_public_audio/sources.json", "src/course_services/day2_meeting_workflow.py", "scripts/day2_public_audio.py", "output/course-labs/day2-v2/02_inputs.json"],
    command: "python scripts/day2_public_audio.py resolve --path-only",
    failure: "공개 MP3를 선택하고 실제로는 합성 fixture 전사를 결과처럼 보여준다.",
    recovery: "public live STT와 fixture WAV·TXT 쌍을 다른 source_mode로 남기고 섞지 않는다.",
    codex: "세 adapter의 정상·빈 TXT·손상 음성·source 혼용 test를 작성한다.",
    normalTest: "세 입력이 각각 다른 source_mode와 segment evidence를 남긴다.",
    boundaryTest: "live STT 실패는 다른 음성의 fixture 전사로 조용히 대체되지 않는다.",
    serviceCase: "회의 도구가 달라도 같은 결과 계약을 쓰는 입력층",
    screenshot: ["public-korean-meeting-source.png", "https://commons.wikimedia.org/wiki/File:2026%EB%85%84_8%EC%9B%94_26%EC%9D%BC_-_%EC%95%88%EB%8F%99_%EC%B5%9C%EA%B3%A0%EC%9C%84%EC%9B%90%ED%9A%8C%EC%9D%98_%EC%83%9D%EC%A4%91%EA%B3%84_-_%EB%8D%94%EB%B6%88%EC%96%B4%EB%AF%BC%EC%A3%BC%EB%8B%B9.webm"],
  }),
  P(11, "도메인 맥락과 MCP 정책", {
    outcome: "업무 도메인·기존 맥락·외부 자료 탐색 범위를 사용자가 통제한다.",
    why: "Notion·Confluence·Slack을 많이 읽는 것과 필요한 근거를 잘 찾는 것은 다르다.",
    artifact: "03_domain_context.json",
    terms: [T("Domain context", "업계 용어·제품·의사결정 기준"), T("MCP", "Desktop AI가 외부 도구를 호출하는 연결 계약"), T("Retrieval policy", "무엇을 언제까지 읽을지의 규칙"), T("Least privilege", "필요한 읽기 권한만 주는 원칙")],
    pipeline: ["도메인 설명", "최근 범위", "읽기 계획", "근거 수집", "민감정보 제외"],
    files: ["src/course_services/day2_meeting_workflow.py", "materials/day2/Codex_Claude_대화_시나리오.md", "tests/test_day2_meeting_workflow.py", "output/course-labs/day2-v2/03_domain_context.json"],
    command: "python -m pytest -q tests/test_day2_meeting_workflow.py -k context",
    failure: "회의명이 비슷하다는 이유로 전체 workspace와 장기 대화를 무제한으로 읽는다.",
    recovery: "회의자·기간·프로젝트·출처를 제한하고 도구 계획을 사람이 확인한다.",
    codex: "요약에 필요한 MCP 읽기만 계획하고 쓰기 도구를 제외하는 policy test를 만든다.",
    normalTest: "각 근거에 source·time window·reason이 남고 write tool은 계획에 없다.",
    boundaryTest: "외부 고객·비공개 채널·기간 밖 문서는 POLICY_BLOCKED다.",
    serviceCase: "회의 전후의 결정 배경만 찾아 맥락을 복원하는 Desktop Agent",
    screenshot: ["mcp-context-policy.png", "https://modelcontextprotocol.io/introduction"],
  }),
  P(12, "MeetingRecord 결과 계약", {
    outcome: "목적·이전 맥락·요약·참석자 관점·To Do·단중장기 통찰을 근거와 구조화한다.",
    why: "담당자·기한·감정 상태를 추측하면 회의록이 아니라 조직 리스크가 된다.",
    artifact: "04_strategy_compare.json",
    terms: [T("Schema", "결과 필드와 형식의 약속"), T("Evidence", "결과를 뒷받침하는 원문 구간"), T("Nullable", "확실하지 않은 값을 비워 두는 설계"), T("Well-being", "부하·갈등·미해결을 단정 없이 표시하는 검토 관점")],
    pipeline: ["목적·맥락", "발화자별 관점", "결정·To Do", "단중장기 통찰", "evidence·null 검증"],
    files: ["src/course_services/day2_meeting_workflow.py", "tests/test_day2_meeting_workflow.py", "materials/day2/day2_service_lab.ipynb", "output/course-labs/day2-v2/04_strategy_compare.json"],
    command: "python -m pytest -q tests/test_day2_meeting_workflow.py -k record",
    failure: "원문에 없는 owner·due date·개인의 생각을 그럴듯하게 보완한다.",
    recovery: "미상값은 null·CONFIRM_REQUIRED로 두고 사실 필드에 evidence ID를 요구한다.",
    codex: "MeetingRecord schema와 근거 누락·unknown owner·extra field test를 함께 만든다.",
    normalTest: "회의 목적부터 단중장기 통찰까지 evidence와 함께 validate된다.",
    boundaryTest: "근거 없는 개인 성향 판단·진단·자동 이메일은 차단된다.",
    serviceCase: "판단·미해결·부하를 함께 보여주는 Well-being 회의기록",
    screenshot: ["meeting-record-schema-local.png", "local:src/course_services/day2_meeting_workflow.py"],
  }),
  P(13, "Codex·Claude 시나리오 설계", {
    outcome: "단계별 대화와 한 번의 Harness 요청을 비교하고 여러 시나리오를 test로 고정한다.",
    why: "상위 모델은 설계 파트너이지 통제를 넘길 대상이 아니다.",
    artifact: "05_workflow_runs.json",
    terms: [T("Scenario tree", "입력·목적·실패에 따른 여러 경로"), T("Harness", "목표·허용 범위·test·금지 행동을 함께 준 작업 계약"), T("Codex", "코드 수정·test·리뷰를 함께 하는 개발 Agent"), T("Independent review", "다른 session이 누락과 경계를 다시 보는 검토")],
    pipeline: ["시나리오 3개", "완료 조건", "Codex 최소 diff", "Claude 독립 리뷰", "사람 merge"],
    files: ["materials/day2/Codex_Claude_대화_시나리오.md", "src/course_services/day2_meeting_workflow.py", "tests/test_day2_meeting_workflow.py", "output/course-labs/day2-v2/05_workflow_runs.json"],
    command: "git diff -- src/course_services/day2_meeting_workflow.py tests/test_day2_meeting_workflow.py",
    failure: "'알아서 Agent를 만들어줘'라고만 요청해 권한·비용·실패 경계가 사라진다.",
    recovery: "한 턴에는 한 책임만 주고 정상·경계 test 통과 후 범위를 늘린다.",
    codex: "Meet·ClovaNote·audio와 미승인 외부 쓰기 차단 test를 먼저 요청한다.",
    normalTest: "세 시나리오가 같은 결과 계약과 다른 입력 경로를 사용한다.",
    boundaryTest: "test 미실행·.env 변경·외부 게시 추가 중 하나라도 있으면 HOLD다.",
    serviceCase: "ChatGPT/Codex 5.6 Sol ultra와 Claude 상위 모델을 개발 동료로 쓰는 작업법",
    screenshot: ["codex-conversation-day2-local.png", "https://learn.chatgpt.com/docs/codex/cli"],
  }),
  P(14, "LLM Provider와 비용 경계", {
    outcome: "fixture·Ollama·OpenAI API·Codex CLI·Claude Code를 같은 계약 뒤에 두고 비용과 가용성을 표시한다.",
    why: "Agent는 여러 번 생각하고 도구를 호출해 단일 LLM 요약보다 비용·지연·오류 면적이 커진다.",
    artifact: "06_provider_diagnostics.json",
    terms: [T("Provider", "모델을 실행하는 서비스나 로컬 엔진"), T("API opt-in", "키·비용·전송을 알고 명시적으로 켜는 경로"), T("Fallback", "실패 시 정해진 대체 경로"), T("Budget", "호출 수·token·시간 한도")],
    pipeline: ["provider 진단", "model 가용성", "비용 한도", "schema 검증", "fallback reason"],
    files: ["src/openai_provider.py", "src/course_services/day2_meeting_workflow.py", ".env.sample", "output/course-labs/day2-v2/06_provider_diagnostics.json"],
    command: "codex login status",
    failure: "API key를 Notebook에 적거나 모델 미지원 오류를 fixture 성공으로 숨긴다.",
    recovery: "key는 env로만 읽고 requested·used provider·model·fallback_reason을 남긴다.",
    codex: "gpt-5.6-luna를 기본 후보로 두되 실제 계정 가용성과 auth·model·timeout 오류를 검증한다.",
    normalTest: "선택 provider가 MeetingRecord schema와 provider_used를 반환한다.",
    boundaryTest: "key 미설정·model 미지원·timeout이 secret 노출 없이 stable reason으로 남는다.",
    serviceCase: "로컬 프라이버시·구독형 CLI·종량제 API를 상황별로 바꾸는 모델층",
    screenshot: ["meeting-intelligence-provider-status-local.png", "https://developers.openai.com/api/docs/models/gpt-5.6-luna"],
  }),
  P(15, "LangGraph 사람 검증", {
    outcome: "고정 순서와 예외 분기를 Graph로 보이고 approve·edit·reject 이후만 초안을 저장한다.",
    why: "LangGraph는 AI가 아니라 AI와 코드가 어디서 멈추고 다시 시작할지 표현하는 상태 기계다.",
    artifact: "07_human_review.json",
    terms: [T("State", "각 단계가 공유하는 현재 결과"), T("Node", "하나의 책임을 실행하는 단계"), T("Interrupt", "사람 판단을 기다리며 멈추는 지점"), T("Draft", "승인 전이라 외부에 반영되지 않은 결과")],
    pipeline: ["입력 정규화", "맥락 계획", "회의록 생성", "evidence 검증", "interrupt·초안"],
    files: ["src/course_services/day2_meeting_workflow.py", "materials/day2/day2_service_lab.ipynb", "tests/test_day2_meeting_workflow.py", "output/course-labs/day2-v2/07_human_review.json"],
    command: "python -m pytest -q tests/test_day2_meeting_workflow.py -k review",
    failure: "READY를 사람 승인으로 오해해 Notion·Confluence·이메일에 바로 쓴다.",
    recovery: "READY_FOR_REVIEW와 APPROVED를 다른 상태로 두고 외부 adapter를 호출하지 않는다.",
    codex: "approve·edit·reject·unknown evidence·미승인 export를 각각 상태 전이 test로 고정한다.",
    normalTest: "approve는 MD·email draft를 만들지만 external_write=false를 유지한다.",
    boundaryTest: "reject·unknown evidence·정책 위반은 외부 반영 없이 HOLD다.",
    serviceCase: "원문·담당·기한·톤을 확인한 뒤에만 공유를 준비하는 흐름",
    screenshot: ["langgraph-interrupt-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"],
  }),
  P(16, "Desktop 선물 패키지", {
    outcome: "세 입력·도메인 맥락·결과 선택·사람 검증을 macOS·Windows 앱으로 전달한다.",
    why: "일반인에게는 Notebook 성공보다 설치·첫 실행·오류 복구·결과 저장이 서비스의 품질이다.",
    artifact: "08_export_drafts.json",
    terms: [T("Desktop app", "일반인이 입력과 결과를 다루는 로컬 프로그램"), T("Container", "같은 실행 환경을 묶은 단위"), T("Integration plan", "승인 후 어떤 외부 도구에 쓸지의 계획"), T("Unsigned", "조직 코드 서명이 아직 없는 교육용 패키지")],
    pipeline: ["입력 선택", "도메인 맥락", "Workflow·Agent", "사람 검증", "MD·email 초안"],
    files: ["desktop-app/meeting-intelligence/README.md", "desktop-app/meeting-intelligence/docker-compose.yml", "materials/day2/day2_service_lab.ipynb", "output/course-labs/day2-v2/08_export_drafts.json"],
    command: "cd desktop-app/meeting-intelligence && python -m pytest -q && go test ./...",
    failure: "강사의 로그인·캐시·경로에서만 되는 Demo를 배포 가능한 제품으로 오해한다.",
    recovery: "fixture 완주를 기본으로 두고 STT·Ollama·CLI·API를 선택 확장으로 분리한다.",
    codex: "API·UI·Docker·Windows EXE·macOS PKG가 같은 schema와 port를 쓰는지 검증한다.",
    normalTest: "세 입력 중 하나로 MeetingRecord·MD·email draft를 만들고 검토 상태를 보여준다.",
    boundaryTest: "미로그인·STT 실패·미승인·MCP 쓰기 요청은 외부 쓰기 없이 HOLD다.",
    serviceCase: "도구가 달라도 자신의 맥락과 톤을 유지하는 개인용 회의기록 Agent",
    screenshot: ["meeting-intelligence-desktop-local.png", "local:desktop-app/meeting-intelligence/README.md"],
  }),
];

export const COURSE_DAYS = {
  2: {
    deckTitle: "Day 2 · 회의기록 Agent 제작",
    subtitle: "3가지 입력 · 도메인 맥락 · 사람 검증 · Desktop App",
    service: "Well-being Meeting Record",
    legacyPeriods: [
      P(9, "공개 회의 음성과 오디오 계약", {
        outcome: "license·출처·길이·채널·샘플링레이트를 확인하고 처리 가능 여부를 판단한다.",
        why: "실제 회의 음성은 모델 성능뿐 아니라 이용 허가와 개인정보 경계까지 입력 계약에 포함해야 한다.",
        artifact: "audio_metadata.json",
        terms: [T("License", "자료를 복제·가공·배포할 수 있는 조건"), T("Codec", "음성을 저장하는 압축 방식"), T("Sample rate", "1초를 몇 번 측정했는지"), T("Channel", "mono·stereo 같은 음성 통로 수")],
        pipeline: ["source manifest 확인", "license·SHA256 검증", "workspace 경로 확인", "audio metadata 읽기", "public 또는 fixture 선택"],
        files: ["data/day2_public_audio/sources.json", "scripts/day2_public_audio.py", "materials/day2/공개_한국어_회의음성_가이드.md", "src/meeting_demo.py"],
        command: "python scripts/day2_public_audio.py resolve",
        failure: "웹에 공개됐다는 이유만으로 이용 조건을 확인하지 않고 원본을 수업 저장소에 넣는다.",
        recovery: "CC 허용 원본만 attribution과 hash를 남기고, 준비되지 않으면 합성 fixture로 같은 계약을 실행한다.",
        codex: "공개 음성 resolve와 metadata 검사를 분리하고 누락 파일·hash 불일치·경로 이탈 test를 추가한다.",
        normalTest: "출처·license·audio path·metadata가 구조화 결과로 반환된다.",
        boundaryTest: "원본 미준비와 workspace 이탈은 fallback reason 또는 WORKSPACE_PATH_BLOCKED로 끝난다.",
        serviceCase: "고객 상담 녹음이 들어오기 전에 포맷과 보존 정책을 검사하는 업로드 단계",
        screenshot: ["public-korean-meeting-source.png", "https://commons.wikimedia.org/wiki/File:2026%EB%85%84_8%EC%9B%94_26%EC%9D%BC_-_%EC%95%88%EB%8F%99_%EC%B5%9C%EA%B3%A0%EC%9C%84%EC%9B%90%ED%9A%8C%EC%9D%98_%EC%83%9D%EC%A4%91%EA%B3%84_-_%EB%8D%94%EB%B6%88%EC%96%B4%EB%AF%BC%EC%A3%BC%EB%8B%B9.webm"],
      }),
      P(10, "faster-whisper 로컬 STT Adapter", {
        outcome: "CPU int8 환경에서 한국어 음성을 segment와 timestamp로 전사한다.",
        why: "모델 호출과 나머지 업무 로직을 분리해야 GPU·모델·provider를 바꿀 수 있다.",
        artifact: "transcript.json",
        terms: [T("Whisper", "음성을 문자로 바꾸는 모델 계열"), T("faster-whisper", "CTranslate2 기반 실행 구현"), T("int8", "메모리를 줄이는 계산 형식"), T("Segment", "시작·끝 시각이 붙은 발화 조각")],
        pipeline: ["모델 load", "VAD 적용", "beam search", "segment 순회", "JSON 안전 float 변환"],
        files: ["src/meeting_demo.py", "requirements-stt-optional.txt", "data/demo_meeting.wav", "output/day2-stt-lab/transcript.json"],
        command: "python -m src.meeting_demo --audio data/demo_meeting.wav --model small --device cpu --compute-type int8",
        failure: "모델 download나 GPU OOM 때문에 후속 수업 전체가 멈춘다.",
        recovery: "local_files_only·CPU int8·작은 모델·reviewed fixture 순서로 내려간다.",
        codex: "provider adapter가 같은 transcript contract를 반환하는지 test로 고정한다.",
        normalTest: "segment마다 start·end·text가 있고 float가 JSON 직렬화된다.",
        boundaryTest: "STT package가 없으면 fixture와 STT_FALLBACK_USED를 함께 남긴다.",
        serviceCase: "사내망에서 원본 음성을 외부로 보내지 않는 상담 품질 분석",
        screenshot: ["whisper-cpp-official.png", "https://github.com/ggerganov/whisper.cpp"],
      }),
      P(11, "STT 품질 Gate", {
        outcome: "무음·반복·낮은 확률·언어 불일치를 품질 flag로 분리한다.",
        why: "문자가 생성됐다는 사실만으로 회의 결과를 만들면 이름과 숫자 오류가 그대로 번진다.",
        artifact: "quality_gate.json",
        terms: [T("VAD", "말소리 구간을 먼저 찾는 처리"), T("no-speech", "해당 구간이 무음일 가능성"), T("WER", "정답 전사 대비 단어 오류율"), T("Diarization", "누가 말했는지 구분하는 처리")],
        pipeline: ["segment metric 수집", "반복·무음 탐지", "언어·WER 확인", "화자 구분 검토", "READY 또는 HOLD"],
        files: ["src/meeting_demo.py", "tests/test_meeting_agent_workflow.py", "data/demo_meeting_transcript.txt", "output/day2-stt-lab/meeting_result.json"],
        command: "python -m pytest -q tests/test_meeting_agent_workflow.py",
        failure: "낮은 품질 segment 하나를 전체 성공으로 숨긴다.",
        recovery: "flagged segment와 timestamp만 사람에게 보여주고 accept·edit·reject를 받는다.",
        codex: "품질 threshold 변경이 기존 정상 음성을 HOLD로 만들지 회귀 test를 작성한다.",
        normalTest: "한국어·충분한 길이·무 flag일 때 READY다.",
        boundaryTest: "fallback·짧은 전사·reference 유사도 저하는 HOLD다.",
        serviceCase: "회의록 생성 전에 고유명사와 금액 구간만 운영자가 spot check",
        screenshot: ["google-meet-transcript-official.png", "https://support.google.com/meet/answer/12849897"],
      }),
      P(12, "회의록 Schema와 Pydantic 계약", {
        outcome: "summary·decision·action item·evidence를 Pydantic 계약으로 만든다.",
        why: "자유로운 문장은 읽기 좋지만 downstream 자동화가 실패해도 원인을 찾기 어렵다.",
        artifact: "meeting_schema.json",
        terms: [T("Schema", "결과 필드와 형식의 약속"), T("Pydantic", "Python 데이터 검증 도구"), T("Structured Output", "정해진 구조로 받는 모델 결과"), T("null", "원문에 값이 없음을 정직하게 표시")],
        pipeline: ["필수 필드 선언", "type·범위 검사", "추가 필드 차단", "evidence 확인", "validation error 반환"],
        files: ["src/langchain_lab.py", "src/course_services/meeting_service.py", "tests/test_langchain_langgraph_lab.py", "materials/day2/day2_service_lab.ipynb"],
        command: "python -m src.langchain_lab --provider fixture",
        failure: "원문에 없는 담당자와 날짜를 빈칸 대신 추측한다.",
        recovery: "미상값은 null로 두고 evidence가 없는 Action Item은 HOLD한다.",
        codex: "회의 schema에 필드를 추가하고 extra=forbid·누락 field test를 함께 만든다.",
        normalTest: "세 개 Action Item이 evidence_ids와 함께 validate된다.",
        boundaryTest: "automatic_email=true 또는 evidence 누락은 validation error다.",
        serviceCase: "회의 요약을 Jira·Notion·메일로 보내기 전 공통 계약",
        screenshot: ["langchain-lcel-demo-local.png", "https://docs.langchain.com/oss/python/langchain/overview"],
      }),
      P(13, "발화 단위 Chunking", {
        outcome: "timestamp와 evidence ID를 잃지 않는 chunk를 만든다.",
        why: "글자 수만 자르면 담당자·결정·근거가 서로 다른 chunk로 갈라진다.",
        artifact: "meeting_chunks.json",
        terms: [T("Chunk", "모델에 넣을 작은 입력 묶음"), T("Overlap", "경계 문맥을 이어 주는 중복 구간"), T("Map", "chunk별 초안을 만드는 단계"), T("Reduce", "여러 초안을 하나로 합치는 단계")],
        pipeline: ["segment 정렬", "길이 누적", "경계에서 close", "한 segment overlap", "chunk ID 저장"],
        files: ["src/course_services/meeting_service.py", "tests/test_course_services.py", "data/meeting_sample_ko_12min.txt", "materials/day2/day2_service_lab.ipynb"],
        command: "python -m pytest -q tests/test_course_services.py -k meeting_chunks",
        failure: "overlap 때문에 같은 Action Item이 두 번 생성된다.",
        recovery: "evidence ID 기반 deduplication과 최종 사람 검토를 적용한다.",
        codex: "segment 경계를 보존하는 chunk 함수와 작은 max_chars failure test를 작성한다.",
        normalTest: "모든 segment ID가 적어도 한 chunk에 존재한다.",
        boundaryTest: "max_chars<40과 음수 overlap은 명시 오류다.",
        serviceCase: "10분 이상 상품 운영 회의를 결정·담당자·기한으로 축약",
        screenshot: ["jupyter-lab-official.png", "https://jupyter.org/"],
      }),
      P(14, "LangChain과 CLI Provider Bridge", {
        outcome: "fixture·Ollama·Codex CLI·Claude Code가 같은 MeetingBrief 계약을 반환하게 한다.",
        why: "로그인된 공식 CLI와 로컬 모델의 차이를 adapter에서 흡수해야 업무 로직과 인증 정보를 분리할 수 있다.",
        artifact: "meeting_brief.json",
        terms: [T("Runnable", "같은 invoke 계약으로 실행되는 구성요소"), T("LCEL", "Runnable을 연결하는 표현 방식"), T("Host bridge", "container가 localhost의 공식 CLI만 호출하는 경계"), T("CLI login", "공식 도구가 관리하는 사용자 인증")],
        pipeline: ["provider 상태 진단", "prompt 구성", "localhost bridge", "Pydantic parse", "policy·fallback 기록"],
        files: ["src/langchain_lab.py", "desktop-app/meeting-intelligence/main.go", "desktop-app/meeting-intelligence/README.md", "tests/test_langchain_langgraph_lab.py"],
        command: "codex login status",
        failure: "웹 로그인 cookie나 credential 파일을 container에 복사해 인증을 재사용한다.",
        recovery: "공식 Codex·Claude CLI 로그인만 host bridge에서 사용하고, 미로그인은 Ollama 또는 fixture로 분리한다.",
        codex: "CLI 상태·timeout·invalid JSON을 stable provider error로 바꾸고 secret 미출력 test를 추가한다.",
        normalTest: "사용 가능한 provider가 같은 필수 field와 automatic_email=false를 반환한다.",
        boundaryTest: "CLI 미설치·미로그인·timeout은 credential 노출 없이 fallback reason을 남긴다.",
        serviceCase: "비용·보안·지연에 따라 로컬과 API 모델을 교체하는 회의 서비스",
        screenshot: ["meeting-intelligence-provider-status-local.png", "https://learn.chatgpt.com/docs/auth"],
      }),
      P(15, "Action Item 근거 검증", {
        outcome: "모든 결정과 할 일을 원문 segment ID에 연결한다.",
        why: "담당자와 기한을 잘못 붙이면 회의 자동화가 오히려 조정 비용을 만든다.",
        artifact: "validated_meeting_brief.json",
        terms: [T("Evidence", "결과를 뒷받침하는 원문 구간"), T("Grounding", "출력 내용을 입력 근거에 묶는 것"), T("Hallucination", "원문에 없는 내용을 만든 오류"), T("Spot check", "위험 구간만 사람이 확인")],
        pipeline: ["결정 추출", "Action Item 추출", "evidence ID 연결", "미상값 null", "사람 승인"],
        files: ["src/meeting_agent_workflow.py", "src/course_services/meeting_service.py", "tests/test_meeting_agent_workflow.py", "output/day1-meeting-agent-ollama/workflow_result.json"],
        command: "python -m src.meeting_agent_workflow --help",
        failure: "evidence ID가 존재하지만 실제 문장과 의미가 맞지 않는다.",
        recovery: "구조 검사는 code evaluator, 의미 검사는 표본 human review로 나눈다.",
        codex: "Action Item evidence 누락·unknown ID를 각각 재현하는 test를 추가한다.",
        normalTest: "모든 evidence ID가 known segment에 존재한다.",
        boundaryTest: "없는 s99를 가리키면 ACTION_n_UNKNOWN_EVIDENCE다.",
        serviceCase: "회의 후 담당 업무를 자동 제안하되 게시 전 원문 근거를 확인",
        screenshot: ["langgraph-interrupt-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"],
      }),
      P(16, "Golden Set과 Desktop App", {
        outcome: "Golden Set으로 품질을 판정하고 같은 결과를 Docker 기반 macOS·Windows 앱에서 재현한다.",
        why: "Notebook 한 번의 성공이 아니라 설치·실행·오류 복구·결과 저장까지 재현돼야 실제 소프트웨어가 된다.",
        artifact: "day2_eval_cases.json",
        terms: [T("Golden case", "팀이 합의한 대표 입력과 기대 결과"), T("Container", "같은 실행 환경을 묶은 단위"), T("Launcher", "Docker 실행과 브라우저 열기를 담당하는 프로그램"), T("Release gate", "배포 여부를 가르는 기준")],
        pipeline: ["golden 평가", "fixture smoke test", "Docker image", "Windows EXE·macOS PKG", "사람 release 판단"],
        files: ["desktop-app/meeting-intelligence/README.md", "desktop-app/meeting-intelligence/docker-compose.yml", "materials/day2/day2_service_lab.ipynb", "output/course-labs/day2/08_day2_scorecard.json"],
        command: "python -m pytest -q tests/test_meeting_agent_workflow.py tests/test_course_services.py",
        failure: "로그인된 개발자 컴퓨터에서만 되는 Demo를 모든 수강생이 실행 가능한 앱으로 오해한다.",
        recovery: "fixture smoke test를 기본으로 두고 Docker·CLI·Ollama 준비 상태를 시작 화면에서 분리해 보여준다.",
        codex: "Docker app·launcher·README가 같은 port와 schema를 쓰는지 test하고 package checksum을 생성한다.",
        normalTest: "fixture 앱이 READY 결과를 저장하고 Windows EXE·macOS PKG build가 생성된다.",
        boundaryTest: "STT HOLD·unknown evidence·미로그인은 외부 쓰기 없이 HOLD 또는 fallback으로 끝난다.",
        serviceCase: "현업에서는 상담/회의 유형별 scorecard, 포트폴리오에는 실패 사례 3건",
        screenshot: ["meeting-intelligence-desktop-local.png", "local:desktop-app/meeting-intelligence/README.md"],
      }),
    ],
    periods: DAY2_PERIODS_V2,
  },
  3: {
    deckTitle: "Day 3 · 코드 리뷰 Agent",
    subtitle: "변경 라인 · Test 근거 · 리뷰 평가",
    service: "Review Intelligence Service",
    periods: [
      P(17, "코드 리뷰 기준과 Severity", {
        outcome: "P0~P3 severity와 actionable finding 기준을 합의한다.", why: "스타일 지적이 많아질수록 중요한 correctness 오류가 묻힌다.", artifact: "review_rubric.md",
        terms: [T("Finding", "한 가지 문제와 교정 제안"), T("Severity", "사용자 영향과 긴급도"), T("False positive", "문제가 아닌데 문제라고 한 결과"), T("Confidence", "근거에 대한 확신 정도")],
        pipeline: ["변경 확인", "사용자 영향", "재현 조건", "근거 라인", "가장 작은 교정"], files: ["AGENTS.md", "src/course_services/contracts.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day3/day3_service_lab.ipynb"],
        command: "python -m pytest -q tests/test_course_services.py -k maps_findings", failure: "모든 의견을 P1으로 부풀려 개발자가 경고를 무시한다.", recovery: "correctness·security·data loss·contract break에 집중하고 style은 linter에 맡긴다.", codex: "AGENTS.md 리뷰 기준을 읽고 바뀐 라인에만 finding을 작성하게 한다.", normalTest: "한 finding에는 path·line·severity·근거·제안이 모두 있다.", boundaryTest: "변경과 무관한 파일 의견은 게시 후보에서 제외한다.", serviceCase: "작은 팀의 PR 대기 시간을 줄이는 첫 번째 자동 검토",
        screenshot: ["codex-cli-official.png", "https://developers.openai.com/codex/cli"],
      }),
      P(18, "Unified Diff와 Line Mapping", {
        outcome: "hunk header로 새 파일 line number를 복원한다.", why: "내용이 맞아도 line mapping이 틀리면 GitHub comment는 422 또는 엉뚱한 위치에 붙는다.", artifact: "parsed_hunks.json",
        terms: [T("Diff", "변경 전후 차이"), T("Hunk", "연속된 변경 구간"), T("Old line", "변경 전 파일의 줄"), T("New line", "변경 후 파일의 줄")], pipeline: ["+++ target 확인", "@@ header parse", "context는 양쪽 증가", "삭제는 old만 증가", "추가는 new에 기록"], files: ["src/course_services/review_service.py", "tests/test_course_services.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day3/day3_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k unified_diff", failure: "파일 header와 코드의 + 기호를 같은 것으로 처리한다.", recovery: "+++ header를 먼저 분리하고 hunk 안의 추가 라인만 수집한다.", codex: "rename·new file·삭제 only diff를 포함한 parser boundary test를 제안받는다.", normalTest: "추가된 9·11·12번 줄에 finding이 매핑된다.", boundaryTest: "absolute path와 hunk 없는 입력은 구조화 실패다.", serviceCase: "GitHub·GitLab에서 공통으로 쓰는 diff 분석 core",
        screenshot: ["github-repository-quickstart-official.png", "https://docs.github.com/repositories/creating-and-managing-repositories/quickstart-for-repositories"],
      }),
      P(19, "리뷰 Context Pack", {
        outcome: "변경 파일·직접 호출부·관련 test만 context pack으로 고른다.", why: "파일을 많이 넣으면 정확도가 자동으로 오르는 대신 비용과 상충 정보가 늘어난다.", artifact: "context_pack.json",
        terms: [T("Repo context", "변경을 이해하는 데 필요한 저장소 정보"), T("Dependency", "변경 코드가 의존하는 대상"), T("Call site", "함수를 실제 호출하는 위치"), T("Context budget", "한 번에 전달할 문맥 한도")], pipeline: ["changed path", "관련 symbol", "가까운 test", "정책 문서", "불필요 문맥 제외"], files: ["AGENTS.md", "src/course_services/review_service.py", "tests/test_course_services.py", "README.md"], command: "rg -n \"run_review_service|ReviewFinding\" src tests", failure: "비밀키·대용량 로그·무관한 output까지 context에 넣는다.", recovery: "rg로 후보를 좁히고 secret·generated output을 명시적으로 제외한다.", codex: "저장소를 이해하되 수정 전 관련 파일과 test를 먼저 나열하게 한다.", normalTest: "context pack에 changed_paths와 test_candidates가 남는다.", boundaryTest: "workspace 밖·.env·실행 cache는 context에서 제외한다.", serviceCase: "수천 파일 monorepo에서 리뷰 latency와 비용을 줄이는 selection",
        screenshot: ["vscode-repo-workspace-local.png", "https://code.visualstudio.com/docs/editor/workspaces"],
      }),
      P(20, "ReviewFinding 결과 계약", {
        outcome: "ReviewFinding과 ReviewReport를 Pydantic으로 검증한다.", why: "자유 문장은 deduplication·line comment·평가에 다시 쓰기 어렵다.", artifact: "review_report.json",
        terms: [T("Contract", "호출자와 구현 사이의 약속"), T("extra=forbid", "모르는 필드를 거부"), T("Error code", "복구 판단에 쓰는 이름"), T("Automatic publish", "사람 없이 게시되는 동작")], pipeline: ["finding validate", "line mapping", "report aggregate", "automatic_publish false", "expected failure code"], files: ["src/course_services/contracts.py", "src/course_services/review_service.py", "tests/test_course_services.py", "data/day5_eval/golden_review_findings.json"], command: "python -m pytest -q tests/test_course_services.py", failure: "schema 오류가 raw traceback으로 notebook을 끝낸다.", recovery: "EXPECTED_FAILURE와 error_code로 바꾸고 원인은 trace에 남긴다.", codex: "contract 변경 시 정상·누락 field·extra field test를 함께 갱신한다.", normalTest: "confidence 0~1과 line>=1이 검증된다.", boundaryTest: "automatic_publish=true는 model validation에서 차단된다.", serviceCase: "리뷰 결과를 IDE·PR·대시보드에서 같은 형식으로 재사용",
        screenshot: ["pytest-getting-started-official.png", "https://docs.pytest.org/en/stable/getting-started.html"],
      }),
      P(21, "Prompt Baseline과 의도적 Bug", {
        outcome: "의도적 bug diff에서 baseline finding을 만든다.", why: "실제 PR만으로 튜닝하면 무엇이 개선됐는지 비교할 정답이 없다.", artifact: "baseline_review.json",
        terms: [T("Baseline", "개선 전 비교 기준"), T("Few-shot", "입출력 예시를 prompt에 제공"), T("Rule ID", "같은 오류 유형을 묶는 식별자"), T("Deterministic", "같은 입력에 재현 가능한 결과")], pipeline: ["synthetic diff", "rule baseline", "LLM candidate", "schema validate", "사람 비교"], files: ["data/day3_review_cases/unsafe_pr.diff", "src/course_services/review_service.py", "materials/day3/day3_service_lab.ipynb", "output/day3-review/baseline.json"], command: "python -m pytest -q tests/test_course_services.py -k maps_findings", failure: "LLM이 존재하지 않는 runtime 결과를 근거로 finding을 만든다.", recovery: "diff·static check·실제 test output만 evidence로 허용한다.", codex: "baseline rule 하나를 구현하고 test가 먼저 실패하는지 확인한 뒤 수정한다.", normalTest: "eval·외부 쓰기·broad except 세 finding이 나온다.", boundaryTest: "빈 diff는 그럴듯한 빈 성공이 아니라 EMPTY_DIFF다.", serviceCase: "교육용 bug repo에서 reviewer의 품질 변화 설명",
        screenshot: ["vscode-pytest-19-passed-local.png", "https://code.visualstudio.com/docs/python/testing"],
      }),
      P(22, "정적 분석·LLM Hybrid Review", {
        outcome: "ruff·pytest 결과와 의미 리뷰를 한 context로 합친다.", why: "문법·unused import까지 LLM에 맡기면 느리고 일관성도 낮다.", artifact: "hybrid_review.json",
        terms: [T("Static analysis", "코드를 실행하지 않고 규칙으로 검사"), T("Unit test", "작은 기능의 동작을 검증"), T("Hybrid review", "결정론 검사와 의미 검토 결합"), T("Evidence", "실제 명령과 변경 라인")], pipeline: ["ruff", "focused pytest", "diff parse", "LLM review", "deduplicate"], files: ["AGENTS.md", "tests/test_course_services.py", "src/course_services/review_service.py", ".github/workflows/test.yml"], command: "python -m pytest -q tests/test_course_services.py", failure: "실행하지 않은 test를 passed라고 prompt에 써 둔다.", recovery: "command·exit code·stdout 요약을 실행 후 evidence bundle에 넣는다.", codex: "코드를 만든 뒤 focused test와 full suite를 실제로 실행하고 결과를 보고하게 한다.", normalTest: "결정론 finding과 test evidence가 같은 report에 존재한다.", boundaryTest: "test 미실행은 READY_FOR_HUMAN_MERGE가 아니다.", serviceCase: "PR이 열리면 자동 검사 후 개발자가 고위험 finding만 검토",
        screenshot: ["vscode-pytest-25-passed-local.png", "https://code.visualstudio.com/docs/python/testing"],
      }),
      P(23, "Precision·Recall 기반 평가", {
        outcome: "golden finding과 predicted finding을 exact key로 비교한다.", why: "많이 지적하는 reviewer가 실제로 더 좋은 reviewer라는 보장은 없다.", artifact: "review_eval.json",
        terms: [T("Precision", "제기한 문제 중 맞은 비율"), T("Recall", "잡아야 할 문제 중 찾은 비율"), T("F1", "precision과 recall의 조화 평균"), T("Golden set", "합의된 기대 finding 모음")], pipeline: ["key 정규화", "교집합", "false positive", "false negative", "release gate"], files: ["src/course_services/eval_service.py", "data/day5_eval/golden_review_findings.json", "tests/test_course_services.py", "materials/day3/day3_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k offline_eval", failure: "제목 문구가 조금 달라졌다고 같은 finding을 다른 것으로 센다.", recovery: "path·line·rule_id 같은 안정 key를 평가에 사용한다.", codex: "평가 함수를 구현할 때 empty prediction·empty expected 경계를 test한다.", normalTest: "fixture case precision·recall·F1이 1.0이다.", boundaryTest: "recall 또는 precision 0.8 미만이면 HOLD다.", serviceCase: "모델 교체 전 기존 reviewer보다 나아졌는지 정량 비교",
        screenshot: ["langsmith-evaluation-official.png", "https://docs.langchain.com/langsmith/evaluation"],
      }),
      P(24, "오류 분석과 회귀 방지", {
        outcome: "false positive·false negative 원인을 분류하고 Day 3 report를 만든다.", why: "평균 점수만 보면 특정 언어·파일·위험 유형의 반복 실패가 보이지 않는다.", artifact: "day3_review_report.md",
        terms: [T("Error analysis", "틀린 결과의 패턴을 분류"), T("Regression", "이전보다 나빠진 동작"), T("Ablation", "구성요소를 빼 영향 확인"), T("Human merge", "최종 반영은 사람이 결정")], pipeline: ["실패 목록", "원인 label", "최소 수정", "회귀 test", "commit·tag"], files: ["src/course_services/codex_harness.py", "tests/test_course_services.py", "AGENTS.md", "materials/day3/day3_service_lab.ipynb"], command: "git diff -- src/course_services tests/test_course_services.py", failure: "점수를 올리려고 기존 assertion이나 policy를 약화한다.", recovery: "실패를 대표 test로 추가하고 최소 변경만 허용한다.", codex: "diff를 검토하고 actionable finding만 보고한 뒤 test 증거를 다시 확인한다.", normalTest: "허용된 path·focused test·diff review가 모두 충족된다.", boundaryTest: ".env 변경·secret 탐지·미실행 test 중 하나라도 있으면 HOLD다.", serviceCase: "현업은 merge 보조, 구직자는 리뷰 품질 리포트와 회귀 test를 포트폴리오로 제출",
        screenshot: ["codex-cli-docs-official.png", "https://developers.openai.com/codex/cli"],
      }),
    ],
  },
  4: {
    deckTitle: "Day 4 · GitHub PR 자동화",
    subtitle: "PR 수집 · LangGraph 승인 · 안전한 게시",
    service: "PR Review Automation Service",
    periods: [
      P(25, "PR 자동화는 target을 정확히 읽는 것부터 시작합니다", { outcome: "repository·PR number·head SHA·diff를 fixture에서 읽는다.", why: "대상 commit이 바뀌면 이전 line mapping과 review comment가 stale해진다.", artifact: "pr_target.json", terms: [T("PR", "변경을 검토·병합하는 요청"), T("Commit", "특정 시점의 변경 묶음"), T("Head SHA", "PR 최신 commit 식별자"), T("Review comment", "diff line에 붙는 의견")], pipeline: ["fixture load", "target validate", "head SHA 고정", "diff load", "read-only result"], files: ["data/day4_github/pr_fixture.json", "src/course_services/github_service.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k github", failure: "화면에 보이는 PR 제목만 믿고 repo·number·SHA를 확인하지 않는다.", recovery: "쓰기 전 target 세 필드를 payload와 승인 화면에 다시 표시한다.", codex: "fixture loader에 필수 field·workspace path test를 추가한다.", normalTest: "synthetic fixture가 PullRequestTarget으로 validate된다.", boundaryTest: "필드 누락이나 workspace 밖 fixture는 구조화 오류다.", serviceCase: "사내 repo PR을 읽어 검토 대기열을 만드는 read-only bot", screenshot: ["github-repository-quickstart-official.png", "https://docs.github.com/repositories/creating-and-managing-repositories/quickstart-for-repositories"] }),
      P(26, "토큰은 기능이 아니라 권한과 만료를 가진 비밀입니다", { outcome: "fine-grained token과 최소 repository permission을 설명한다.", why: "교육용 token 하나가 실수로 commit되면 저장소 전체 위험으로 번진다.", artifact: ".env.sample", terms: [T("PAT", "개인 API 접근 토큰"), T("Fine-grained", "대상과 권한을 좁힌 token"), T("Secret", "소스·로그에 남기면 안 되는 값"), T("Least privilege", "필요한 최소 권한만 부여")], pipeline: ["권한 목록", "sandbox repo", ".env local", ".gitignore", "만료·폐기"], files: [".env.sample", ".gitignore", "AGENTS.md", "data/day4_github/pr_fixture.json"], command: "git check-ignore -v .env", failure: "token 값을 notebook output이나 screenshot에 노출한다.", recovery: "존재 여부만 bool로 확인하고 노출된 token은 즉시 폐기·재발급한다.", codex: "secret을 읽거나 출력하지 않는 범위에서 config validation만 구현한다.", normalTest: ".env는 ignore되고 .env.sample만 추적된다.", boundaryTest: "token이 없으면 401을 재시도하지 않고 실행을 중단한다.", serviceCase: "교육에서는 mock, 운영에서는 App token·short-lived credential 고려", screenshot: ["github-rest-auth-official.png", "https://docs.github.com/rest/authentication/authenticating-to-the-rest-api"] }),
      P(27, "REST client는 status code를 복구 결정으로 바꿔야 합니다", { outcome: "read-only PR 조회와 pagination·rate limit 계약을 만든다.", why: "모든 오류를 같은 retry로 처리하면 인증 문제와 rate limit이 장애를 키운다.", artifact: "github_read_result.json", terms: [T("REST", "HTTP resource 단위 API 방식"), T("Pagination", "여러 페이지로 결과를 나눔"), T("Rate limit", "시간당 요청 제한"), T("Retry-After", "다시 요청 가능한 시각 힌트")], pipeline: ["GET request", "status classify", "pagination", "bounded backoff", "structured result"], files: ["src/course_services/github_service.py", "materials/day4/day4_service_lab.ipynb", "AGENTS.md", "output/day4-github/read-result.json"], command: "python -m pytest -q tests/test_course_services.py", failure: "401·403·404·422·429를 모두 세 번 retry한다.", recovery: "재인증·권한 확인·target 확인·diff 갱신·대기 경로를 error code별로 나눈다.", codex: "fake HTTP response로 각 status code의 결정론 test를 작성한다.", normalTest: "200 응답은 target·diff·rate metadata를 반환한다.", boundaryTest: "429만 Retry-After와 최대 횟수 안에서 재시도한다.", serviceCase: "PR 정보를 안전하게 수집하는 ingestion adapter", screenshot: ["git-first-setup-official.png", "https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup"] }),
      P(28, "LangGraph state에는 다음 결정을 위한 값만 둡니다", { outcome: "PR review의 node·edge·conditional edge를 조립한다.", why: "모든 원문과 client 객체를 state에 넣으면 checkpoint와 재시작이 불안정해진다.", artifact: "compiled_review_graph", terms: [T("State", "node 사이에 전달할 명시 데이터"), T("Node", "한 책임을 실행하는 함수"), T("Edge", "다음 실행 순서"), T("Conditional edge", "상태에 따른 분기")], pipeline: ["validate target", "load diff", "review", "human review", "dry-run"], files: ["src/langgraph_lab.py", "src/meeting_agent_workflow.py", "src/course_services/github_service.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "state에 token·client·raw audio를 넣어 checkpoint에 남긴다.", recovery: "ID·status·검증 결과만 state에 두고 외부 자원은 adapter 경계에서 주입한다.", codex: "기존 service 함수를 node로 감싸되 contract를 바꾸지 않게 한다.", normalTest: "approve·edit·reject가 서로 다른 terminal state로 간다.", boundaryTest: "validation error는 publish node에 도달하지 않는다.", serviceCase: "회의 Agent와 PR Agent가 같은 승인 패턴을 재사용", screenshot: ["langgraph-overview-official.png", "https://docs.langchain.com/oss/python/langgraph/overview"] }),
      P(29, "재시작 가능한 workflow는 같은 일을 두 번 하지 않습니다", { outcome: "retry·checkpoint·request ID·idempotency를 연결한다.", why: "interrupt 전후 node가 다시 실행돼도 외부 쓰기는 한 번이어야 한다.", artifact: "checkpoint_and_audit.json", terms: [T("Checkpoint", "중단 시 state 저장"), T("Thread ID", "같은 실행을 이어 가는 식별자"), T("Idempotency", "같은 요청을 반복해도 결과가 한 번인 성질"), T("Backoff", "재시도 간격을 점차 늘림")], pipeline: ["request ID", "checkpoint", "bounded retry", "idempotency lookup", "reuse result"], files: ["src/course_services/github_service.py", "src/langgraph_lab.py", "tests/test_course_services.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k idempotent", failure: "timeout 뒤 동일 comment를 다시 게시한다.", recovery: "target·SHA·body hash를 idempotency key로 저장하고 기존 remote result를 재사용한다.", codex: "같은 plan을 두 번 실행해 publisher call이 1회인지 test한다.", normalTest: "첫 실행은 reused=false, 두 번째는 true다.", boundaryTest: "body나 head SHA가 달라지면 새 승인 대상으로 본다.", serviceCase: "네트워크가 불안한 CI bot의 중복 comment 방지", screenshot: ["langgraph-persistence-official.png", "https://docs.langchain.com/oss/python/langgraph/persistence"] }),
      P(30, "Human Approval은 버튼보다 검토할 정보가 중요합니다", { outcome: "approve·edit·reject interrupt payload를 설계한다.", why: "초안만 보여주고 대상과 근거를 숨기면 사람은 사실상 승인할 수 없다.", artifact: "review_decision.json", terms: [T("Interrupt", "workflow를 멈추고 입력을 기다림"), T("Approve", "초안을 그대로 허용"), T("Edit", "사람이 수정 후 허용"), T("Reject", "외부 쓰기 없이 종료")], pipeline: ["초안 생성", "target 표시", "finding 근거", "사람 결정", "같은 thread resume"], files: ["src/langgraph_lab.py", "src/meeting_agent_workflow.py", "web-demo/app.js", "materials/day4/day4_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "interrupt를 일반 Exception으로 잡아 자동 진행한다.", recovery: "interrupt를 workflow event로 두고 같은 thread_id와 JSON decision으로 resume한다.", codex: "승인 node 전에 외부 쓰기 호출이 존재하지 않는지 diff review한다.", normalTest: "approve가 READY_FOR_EXPORT로 간다.", boundaryTest: "reject는 external_write=false와 REJECTED로 끝난다.", serviceCase: "PR comment·메일·ticket 생성 전에 동일 승인 UI 사용", screenshot: ["langgraph-interrupts-official.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(31, "Dry-run은 실제 게시 직전의 완성된 결과여야 합니다", { outcome: "PR comment body·target·idempotency key를 local JSON으로 만든다.", why: "대충 만든 preview는 실제 API payload와 달라 승인 증거가 되지 못한다.", artifact: "review_comment_plan.json", terms: [T("Dry-run", "외부 쓰기 없이 동일 payload 생성"), T("Payload", "API에 보낼 구조화 데이터"), T("Audit", "누가 무엇을 승인했는지 기록"), T("External write", "외부 시스템 상태를 바꾸는 호출")], pipeline: ["report validate", "comment render", "target bind", "hash key", "READY_FOR_APPROVAL"], files: ["src/course_services/github_service.py", "src/course_services/contracts.py", "tests/test_course_services.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k dry_run", failure: "dry_run=true인데 publisher가 호출된다.", recovery: "DRY_RUN_CANNOT_PUBLISH를 contract로 고정하고 fake publisher call 수를 assert한다.", codex: "dry-run 경계를 건드리는 변경에는 boundary test 없이는 완료하지 않는다.", normalTest: "payload에 repo·PR·SHA·body·key가 있다.", boundaryTest: "dry-run plan은 approval=true여도 publish되지 않는다.", serviceCase: "운영자가 Slack/PR 화면에서 실제 게시 내용을 사전 검토", screenshot: ["langgraph-reject-result-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(32, "실제 GitHub 쓰기는 본인 sandbox에서 한 건만 실행합니다", { outcome: "선택적으로 승인된 comment 한 건을 게시하고 audit ID를 남긴다.", why: "교육 실습이 타인 저장소나 업무 repo를 오염시키면 안 된다.", artifact: "day4_audit_record.json", terms: [T("Sandbox repo", "실습 전용 본인 저장소"), T("Publisher", "외부 API write adapter"), T("Remote ID", "게시 결과 식별자"), T("Rollback", "comment 삭제 또는 commit revert")], pipeline: ["sandbox 확인", "dry-run 검토", "사람 승인", "1회 POST", "response ID 기록"], files: ["materials/day4/day4_service_lab.ipynb", "src/course_services/github_service.py", ".env.sample", "AGENTS.md"], command: "python -m pytest -q tests/test_course_services.py", failure: "교육 코드에 live publisher와 token scope를 기본 포함한다.", recovery: "repo에는 fake publisher만 두고 live adapter는 강사 승인 후 별도 branch에서 연결한다.", codex: "PR 생성·리뷰·test 수정은 돕되 merge와 외부 게시 결정은 사람에게 남긴다.", normalTest: "fake publisher가 한 번 호출되고 remote ID가 audit에 남는다.", boundaryTest: "publisher 미설정·승인 없음·dry-run은 모두 BLOCKED다.", serviceCase: "현업은 GitHub App과 protected branch, 구직자는 sandbox demo recording", screenshot: ["codex-cli-official.png", "https://learn.chatgpt.com/use-cases"] }),
    ],
  },
  5: {
    deckTitle: "Day 5 · 통합·관측·평가·배포",
    subtitle: "서비스 통합 · LangSmith 관측 · 평가 · 배포",
    service: "Agent Operations Console",
    periods: [
      P(33, "Router는 파일 확장자가 아니라 명시된 업무 의도로 분기합니다", { outcome: "meeting_transcript와 code_diff를 같은 entry point에서 실행한다.", why: "모델 추측으로 업무 종류를 고르면 잘못된 tool과 권한이 연결될 수 있다.", artifact: "unified_service_result.json", terms: [T("Router", "입력을 알맞은 workflow로 전달"), T("Input kind", "호출자가 명시한 업무 종류"), T("Adapter", "서로 다른 service 결과를 연결"), T("Boundary", "읽기·쓰기·승인 경계")], pipeline: ["path validate", "input kind 확인", "meeting 또는 review", "공통 result", "사람 승인"], files: ["src/course_services/service_router.py", "src/course_services/meeting_service.py", "src/course_services/review_service.py", "materials/day5/day5_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k router", failure: "내용을 LLM에게 보여주고 업무 종류와 권한을 함께 추측시킨다.", recovery: "input_kind를 API contract로 받고 unsupported type은 거부한다.", codex: "새 service route를 추가할 때 workspace 경계와 external_write=false를 test한다.", normalTest: "회의와 diff가 각각 올바른 service 이름으로 반환된다.", boundaryTest: "unknown kind와 workspace escape는 EXPECTED_FAILURE다.", serviceCase: "한 화면에서 회의·PR 리뷰를 선택 실행하는 내부 도구", screenshot: ["langchain-langgraph-workflow-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/overview"] }),
      P(34, "LangSmith trace는 실행 과정을 질문할 수 있게 만듭니다", { outcome: "project·trace·run·thread의 관계를 이해하고 첫 trace를 남긴다.", why: "최종 JSON만 저장하면 느린 node와 실패 원인을 다시 찾기 어렵다.", artifact: "trace.json 또는 LangSmith run", terms: [T("Project", "관련 실행을 모으는 공간"), T("Trace", "한 요청의 전체 실행 계보"), T("Run", "node·LLM·tool 한 번의 실행"), T("Thread", "대화·재개 실행의 연속성")], pipeline: ["request start", "span 시작", "입력 최소화", "status·latency", "trace close"], files: ["src/observability_lab.py", "src/workflow_service.py", "output/day1-workflow/trace.json", ".env.sample"], command: "python -m src.workflow_service --decision approve --out output/day5-trace", failure: "raw transcript·token·고객 정보를 trace input에 그대로 보낸다.", recovery: "local trace 기본, synthetic/deidentified만 명시 upload, raw content는 제외한다.", codex: "새 node에 latency·status metadata를 추가하되 PII payload를 넣지 않는다.", normalTest: "trace에 span 계층과 READY/HOLD 결정이 남는다.", boundaryTest: "local_only나 key 없음은 upload하지 않고 error code를 반환한다.", serviceCase: "장애 문의에서 request ID로 어느 node가 실패했는지 조회", screenshot: ["langsmith-observability-official.png", "https://docs.langchain.com/langsmith/observability"] }),
      P(35, "운영 dashboard는 예쁜 그래프보다 결정 가능한 신호가 먼저입니다", { outcome: "status·error·latency·provider·cost metadata를 비교한다.", why: "평균 latency 하나만 보면 특정 provider와 실패 유형의 꼬리가 숨겨진다.", artifact: "monitoring_view.md", terms: [T("Tag", "실행을 분류하는 짧은 label"), T("Metadata", "조회·비교용 구조화 값"), T("Latency", "요청부터 결과까지 걸린 시간"), T("Cost", "token·compute 사용 비용")], pipeline: ["tag version", "provider metadata", "node latency", "error code", "READY/HOLD filter"], files: ["src/observability_lab.py", "output/day1-workflow/trace.json", "materials/day5/day5_service_lab.ipynb", "AGENTS.md"], command: "python -m pytest -q tests/test_observability_workflow.py", failure: "성공 trace만 보고 HOLD·reject·fallback을 제외한다.", recovery: "status와 fallback_reason을 같은 dashboard filter에 포함한다.", codex: "추적 field를 늘리기 전에 운영 질문 한 개와 필요한 metadata만 정의한다.", normalTest: "provider_used와 node latency를 필터링할 수 있다.", boundaryTest: "오류 원문 대신 stable error_code와 type만 외부 trace에 남는다.", serviceCase: "모델 교체 후 latency·fallback·HOLD 비율 비교", screenshot: ["langsmith-pricing-official.png", "https://www.langchain.com/pricing"] }),
      P(36, "평가는 같은 dataset으로 baseline과 candidate를 비교해야 합니다", { outcome: "golden review case를 code evaluator로 실행한다.", why: "데모 입력이 매번 달라지면 개선인지 운인지 구분할 수 없다.", artifact: "experiment_result.json", terms: [T("Dataset", "반복 평가할 입력·정답 묶음"), T("Experiment", "특정 버전을 dataset에 실행"), T("Code evaluator", "규칙으로 자동 채점"), T("Candidate", "새로 비교할 구현")], pipeline: ["golden load", "baseline run", "candidate run", "metric compare", "release gate"], files: ["src/course_services/eval_service.py", "data/day5_eval/golden_review_findings.json", "tests/test_course_services.py", "materials/day5/day5_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k offline_eval", failure: "LLM judge 한 개 점수를 객관적 정답처럼 사용한다.", recovery: "schema·line mapping·policy는 code evaluator, 의미 품질은 human sample로 나눈다.", codex: "새 평가 지표에 empty set과 threshold boundary test를 추가한다.", normalTest: "fixture precision·recall·F1이 1.0이다.", boundaryTest: "precision 또는 recall 0.8 미만은 HOLD다.", serviceCase: "릴리스 후보가 기존 version보다 실제로 나아졌는지 비교", screenshot: ["langsmith-evaluation-official.png", "https://docs.langchain.com/langsmith/evaluation"] }),
      P(37, "사람 피드백은 좋아요 버튼보다 판단 이유가 필요합니다", { outcome: "approve·edit·reject와 수정 이유를 label로 남긴다.", why: "단순 thumbs-up은 어떤 오류를 고쳐야 하는지 알려주지 못한다.", artifact: "human_feedback.jsonl", terms: [T("Annotation", "사람이 결과에 붙인 label"), T("Feedback", "실행 품질에 대한 평가"), T("Queue", "검토가 필요한 실행 목록"), T("Reviewer agreement", "검토자 판단 일치 정도")], pipeline: ["HOLD sample", "근거 표시", "사람 결정", "reason label", "dataset 후보"], files: ["src/meeting_agent_workflow.py", "src/langgraph_lab.py", "web-demo/app.js", "materials/day5/day5_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "사람 수정 내용을 곧바로 training data로 재사용한다.", recovery: "동의·비식별·품질 검토 후 별도 dataset 승인을 거친다.", codex: "feedback schema와 allowed label을 구현하고 unknown label을 차단한다.", normalTest: "approve·edit·reject가 reviewer·reason과 저장된다.", boundaryTest: "PII가 있는 raw content는 annotation export에서 제외된다.", serviceCase: "운영자 검토 결과를 다음 prompt·rule 개선 후보로 연결", screenshot: ["langgraph-interrupt-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(38, "운영 가능한 Agent는 개인정보와 장애 대응을 먼저 설명합니다", { outcome: "redaction·retention·access·incident checklist를 만든다.", why: "회의·상담·코드에는 개인 정보와 회사 비밀이 동시에 들어갈 수 있다.", artifact: "ops_checklist.md", terms: [T("PII", "개인을 식별할 수 있는 정보"), T("Redaction", "민감 정보를 가리거나 제거"), T("Retention", "데이터 보관 기간"), T("Incident", "보안·품질 장애 사건")], pipeline: ["classify", "minimize", "redact", "retain/delete", "incident review"], files: ["src/observability_lab.py", "AGENTS.md", ".env.sample", "materials/day1/강사_회의음성_라이브데모_런북.md"], command: "python -m pytest -q tests/test_observability_workflow.py", failure: "편의를 위해 원본 audio와 raw prompt를 무기한 외부에 보관한다.", recovery: "목적·동의·최소수집·보존기한·삭제 경로를 배포 전 결정한다.", codex: "trace scrubber가 token·email·전화번호를 제거하는 정상·실패 test를 만든다.", normalTest: "synthetic·deidentified만 외부 upload 후보가 된다.", boundaryTest: "local_only와 secret 탐지는 upload를 차단한다.", serviceCase: "교육 데모에서 시작해 실제 고객 데이터로 넘어가기 위한 readiness gate", screenshot: ["google-meet-notes-official.png", "https://support.google.com/meet/answer/14754931"] }),
      P(39, "배포 후보는 코드·문서·demo가 같은 버전을 가리켜야 합니다", { outcome: "test·README·sample data·Vercel demo를 release candidate로 묶는다.", why: "코드는 최신인데 화면과 문서가 이전 schema면 사용자는 첫 실행에서 막힌다.", artifact: "release_candidate", terms: [T("Release candidate", "배포 직전 검증 버전"), T("Smoke test", "핵심 경로의 빠른 점검"), T("README", "설치·실행·복구 안내"), T("Demo", "실제 입력과 결과를 보여주는 시연")], pipeline: ["focused tests", "full suite", "README", "demo build", "human release"], files: ["README.md", "web-demo/", "scripts/run_day1_preflight.py", "materials/day5/day5_service_lab.ipynb"], command: "python scripts/run_day1_preflight.py", failure: "Vercel 화면만 동작하고 backend result contract와 다른 mock을 보여준다.", recovery: "Python output JSON을 demo의 단일 input으로 사용하고 schema version을 표시한다.", codex: "기능 구현 후 README·test·demo data가 같은 contract인지 diff로 검토한다.", normalTest: "local fixture로 end-to-end 결과와 demo JSON이 생성된다.", boundaryTest: "build 실패·test 실패·HOLD가 있으면 release candidate가 아니다.", serviceCase: "내부 시연 URL과 재현 가능한 GitHub repo를 한 번에 전달", screenshot: ["langchain-langgraph-workflow-demo-local.png", "https://vercel.com/docs"] }),
      P(40, "최종 발표는 모델 자랑보다 문제·증거·운영 결정을 보여줍니다", { outcome: "3분 demo와 2분 질문으로 서비스 가치를 검증한다.", why: "기능 목록만 보여주면 왜 안전하고 운영 가능한지 판단할 수 없다.", artifact: "final_tag_and_scorecard", terms: [T("Problem", "누구의 어떤 반복 업무인지"), T("Evidence", "실행·test·평가 결과"), T("Trade-off", "선택으로 얻고 포기한 것"), T("Next step", "다음 검증 우선순위")], pipeline: ["문제 30초", "live demo 90초", "실패·HITL 30초", "평가 30초", "질문 2분"], files: ["README.md", "materials/day5/day5_service_lab.ipynb", "output/day1-workflow/", "slides/"], command: "git status --short && python -m pytest -q", failure: "성공 화면만 보여주고 실패·사람 승인·평가를 생략한다.", recovery: "정상 한 건과 대표 HOLD 한 건을 나란히 보여준다.", codex: "발표 전 저장소 구조·README·test 증거를 다시 점검하고 누락만 보완한다.", normalTest: "처음 보는 사람이 repo에서 demo를 재현할 수 있다.", boundaryTest: "비밀키·실제 고객 데이터·자동 외부 쓰기는 발표 자료에 없다.", serviceCase: "재직자는 업무 적용 계획, 구직자는 제품 판단과 검증 능력을 포트폴리오로 제시", screenshot: ["codex-cli-docs-official.png", "https://learn.chatgpt.com/use-cases"] }),
    ],
  },
};

export const DAY_TIMES = [
  ["09:00-09:50", "1차시"],
  ["09:50-10:40", "2차시"],
  ["10:40-11:30", "3차시"],
  ["13:00-13:50", "4차시"],
  ["13:50-14:40", "5차시"],
  ["15:00-15:50", "6차시"],
  ["15:50-16:40", "7차시"],
  ["16:40-17:30", "8차시"],
];

export const CODEX_OFFICIAL_SOURCE = "https://learn.chatgpt.com/use-cases";
export const OPENAI_CODEX_DOCS = "https://developers.openai.com/codex/";
export const CLAUDE_CODE_DESKTOP = "https://code.claude.com/docs/en/desktop";
export const CLAUDE_CODE_QUICKSTART = "https://code.claude.com/docs/en/desktop-quickstart";
