const T = (term, meaning) => [term, meaning];

const PERIOD_TITLES = {
  25: "PR Target과 Fixture",
  26: "GitHub 인증과 최소 권한",
  27: "REST 상태 코드와 복구",
  28: "LangGraph State와 분기",
  29: "Checkpoint와 Idempotency",
  30: "Human Approval과 Interrupt",
  31: "Dry-run Comment Payload",
  32: "Sandbox GitHub 게시",
  33: "Meeting·Review Service Router",
  34: "LangSmith Trace 구조",
  35: "운영 Metadata와 Monitoring",
  36: "Dataset Experiment와 Release Gate",
  37: "Human Feedback과 Annotation",
  38: "PII·Retention·Incident 운영",
  39: "Release Candidate와 Vercel Demo",
  40: "최종 Demo와 Scorecard",
};

const P = (hour, title, config) => ({
  hour,
  title: PERIOD_TITLES[hour] ?? title,
  mode: "강의 12분 · 강사 시연 10분 · Codex 소프트웨어 제작 23분 · 실행 확인 5분",
  ...config,
  screenshot: hour === 22
    ? ["vscode-pytest-19-passed-local.png", config.screenshot[1]]
    : config.screenshot,
});

export const COURSE_DAYS = {
  2: {
    deckTitle: "Day 2 · 한국어 회의 Agent",
    subtitle: "한국어 STT · 회의 구조화 · 근거 검증",
    service: "Meeting Intelligence Service",
    periods: [
      P(9, "오디오 파일 계약과 메타데이터", {
        outcome: "길이·채널·샘플링레이트를 읽고 전사 가능 여부를 판단한다.",
        why: "깨진 입력을 모델 문제로 오해하면 복구 순서가 뒤집힌다.",
        artifact: "audio_metadata.json",
        terms: [T("Codec", "음성을 저장하는 압축 방식"), T("Container", "음성과 메타데이터를 담는 파일 형식"), T("Sample rate", "1초를 몇 번 측정했는지"), T("Channel", "mono·stereo 같은 음성 통로 수")],
        pipeline: ["workspace 경로 확인", "파일 존재 확인", "WAV metadata 읽기", "지원 조건 판정", "전사 또는 구조화 실패"],
        files: ["data/demo_meeting.wav", "data/demo_meeting_transcript.txt", "materials/day2/day2_service_lab.ipynb", "src/meeting_demo.py"],
        command: "python -m src.meeting_demo --help",
        failure: "파일이 없거나 codec을 열 수 없는데 재시도만 반복한다.",
        recovery: "FILE_NOT_FOUND와 UNSUPPORTED_AUDIO를 구분하고 변환 또는 fixture 경로를 안내한다.",
        codex: "오디오 metadata 검사 함수를 작은 책임으로 분리하고 정상·경로 이탈 test를 추가한다.",
        normalTest: "WAV의 길이·rate·channel이 숫자로 반환된다.",
        boundaryTest: "workspace 밖 오디오는 WORKSPACE_PATH_BLOCKED로 끝난다.",
        serviceCase: "고객 상담 녹음이 들어오기 전에 포맷과 보존 정책을 검사하는 업로드 단계",
        screenshot: ["faster-whisper-official.png", "https://github.com/SYSTRAN/faster-whisper"],
      }),
      P(10, "faster-whisper 로컬 STT Adapter", {
        outcome: "CPU int8 환경에서 한국어 음성을 segment와 timestamp로 전사한다.",
        why: "모델 호출과 나머지 업무 로직을 분리해야 GPU·모델·provider를 바꿀 수 있다.",
        artifact: "transcript.json",
        terms: [T("Whisper", "음성을 문자로 바꾸는 모델 계열"), T("faster-whisper", "CTranslate2 기반 실행 구현"), T("int8", "메모리를 줄이는 계산 형식"), T("Segment", "시작·끝 시각이 붙은 발화 조각")],
        pipeline: ["모델 load", "VAD 적용", "beam search", "segment 순회", "JSON 안전 float 변환"],
        files: ["src/meeting_demo.py", "requirements-stt-optional.txt", "data/demo_meeting.wav", "output/day2-stt-lab/transcript.json"],
        command: "python -m src.meeting_demo --audio data/demo_meeting.wav --model small --device cpu --compute-type int8",
        failure: "모델 download나 GPU OOM 때문에 후속 수업 전체가 멈춘다.",
        recovery: "local_files_only·CPU int8·작은 모델·reviewed fixture 순서로 내려간다.",
        codex: "provider adapter가 같은 transcript contract를 반환하는지 test로 고정한다.",
        normalTest: "segment마다 start·end·text가 있고 float가 JSON 직렬화된다.",
        boundaryTest: "STT package가 없으면 fixture와 STT_FALLBACK_USED를 함께 남긴다.",
        serviceCase: "사내망에서 원본 음성을 외부로 보내지 않는 상담 품질 분석",
        screenshot: ["whisper-cpp-official.png", "https://github.com/ggerganov/whisper.cpp"],
      }),
      P(11, "STT 품질 Gate", {
        outcome: "무음·반복·낮은 확률·언어 불일치를 품질 flag로 분리한다.",
        why: "문자가 생성됐다는 사실만으로 회의 결과를 만들면 이름과 숫자 오류가 그대로 번진다.",
        artifact: "quality_gate.json",
        terms: [T("VAD", "말소리 구간을 먼저 찾는 처리"), T("no-speech", "해당 구간이 무음일 가능성"), T("log probability", "모델이 전사에 가진 상대 신뢰"), T("Hotwords", "제품명 등 인식 힌트")],
        pipeline: ["segment metric 수집", "반복 탐지", "언어 확인", "reference 비교", "READY 또는 HOLD"],
        files: ["src/meeting_demo.py", "tests/test_meeting_agent_workflow.py", "data/demo_meeting_transcript.txt", "output/day2-stt-lab/meeting_result.json"],
        command: "python -m pytest -q tests/test_meeting_agent_workflow.py",
        failure: "낮은 품질 segment 하나를 전체 성공으로 숨긴다.",
        recovery: "flagged segment와 timestamp만 사람에게 보여주고 accept·edit·reject를 받는다.",
        codex: "품질 threshold 변경이 기존 정상 음성을 HOLD로 만들지 회귀 test를 작성한다.",
        normalTest: "한국어·충분한 길이·무 flag일 때 READY다.",
        boundaryTest: "fallback·짧은 전사·reference 유사도 저하는 HOLD다.",
        serviceCase: "회의록 생성 전에 고유명사와 금액 구간만 운영자가 spot check",
        screenshot: ["google-meet-transcript-official.png", "https://support.google.com/meet/answer/12849897"],
      }),
      P(12, "회의록 Schema와 Pydantic 계약", {
        outcome: "summary·decision·action item·evidence를 Pydantic 계약으로 만든다.",
        why: "자유로운 문장은 읽기 좋지만 downstream 자동화가 실패해도 원인을 찾기 어렵다.",
        artifact: "meeting_schema.json",
        terms: [T("Schema", "결과 필드와 형식의 약속"), T("Pydantic", "Python 데이터 검증 도구"), T("Structured Output", "정해진 구조로 받는 모델 결과"), T("null", "원문에 값이 없음을 정직하게 표시")],
        pipeline: ["필수 필드 선언", "type·범위 검사", "추가 필드 차단", "evidence 확인", "validation error 반환"],
        files: ["src/langchain_lab.py", "src/course_services/meeting_service.py", "tests/test_langchain_langgraph_lab.py", "materials/day2/day2_service_lab.ipynb"],
        command: "python -m src.langchain_lab --provider fixture",
        failure: "원문에 없는 담당자와 날짜를 빈칸 대신 추측한다.",
        recovery: "미상값은 null로 두고 evidence가 없는 Action Item은 HOLD한다.",
        codex: "회의 schema에 필드를 추가하고 extra=forbid·누락 field test를 함께 만든다.",
        normalTest: "세 개 Action Item이 evidence_ids와 함께 validate된다.",
        boundaryTest: "automatic_email=true 또는 evidence 누락은 validation error다.",
        serviceCase: "회의 요약을 Jira·Notion·메일로 보내기 전 공통 계약",
        screenshot: ["langchain-lcel-demo-local.png", "https://docs.langchain.com/oss/python/langchain/overview"],
      }),
      P(13, "발화 단위 Chunking", {
        outcome: "timestamp와 evidence ID를 잃지 않는 chunk를 만든다.",
        why: "글자 수만 자르면 담당자·결정·근거가 서로 다른 chunk로 갈라진다.",
        artifact: "meeting_chunks.json",
        terms: [T("Chunk", "모델에 넣을 작은 입력 묶음"), T("Overlap", "경계 문맥을 이어 주는 중복 구간"), T("Map", "chunk별 초안을 만드는 단계"), T("Reduce", "여러 초안을 하나로 합치는 단계")],
        pipeline: ["segment 정렬", "길이 누적", "경계에서 close", "한 segment overlap", "chunk ID 저장"],
        files: ["src/course_services/meeting_service.py", "tests/test_course_services.py", "data/meeting_sample_ko_12min.txt", "materials/day2/day2_service_lab.ipynb"],
        command: "python -m pytest -q tests/test_course_services.py -k meeting_chunks",
        failure: "overlap 때문에 같은 Action Item이 두 번 생성된다.",
        recovery: "evidence ID 기반 deduplication과 최종 사람 검토를 적용한다.",
        codex: "segment 경계를 보존하는 chunk 함수와 작은 max_chars failure test를 작성한다.",
        normalTest: "모든 segment ID가 적어도 한 chunk에 존재한다.",
        boundaryTest: "max_chars<40과 음수 overlap은 명시 오류다.",
        serviceCase: "10분 이상 상품 운영 회의를 결정·담당자·기한으로 축약",
        screenshot: ["jupyter-lab-official.png", "https://jupyter.org/"],
      }),
      P(14, "LangChain MeetingBrief Pipeline", {
        outcome: "fixture·Ollama·OpenAI가 같은 MeetingBrief를 반환하게 한다.",
        why: "provider별 코드를 업무 로직에 섞으면 모델 변경이 곧 전체 재개발이 된다.",
        artifact: "meeting_brief.json",
        terms: [T("Runnable", "같은 invoke 계약으로 실행되는 구성요소"), T("LCEL", "Runnable을 연결하는 표현 방식"), T("Adapter", "provider 차이를 흡수하는 층"), T("Fallback", "실패 시 정해진 대체 경로")],
        pipeline: ["prompt 구성", "provider 선택", "structured generation", "Pydantic parse", "policy validate"],
        files: ["src/langchain_lab.py", "src/openai_provider.py", "requirements-local-llm-optional.txt", "tests/test_langchain_langgraph_lab.py"],
        command: "python -m src.langchain_lab --provider ollama --model qwen3:4b",
        failure: "OpenAI 오류가 조용히 fixture 성공처럼 보인다.",
        recovery: "provider_requested·provider_used·fallback_reason을 결과에 함께 남긴다.",
        codex: "새 provider adapter가 기존 MeetingBrief contract와 fallback test를 통과하게 한다.",
        normalTest: "Qwen과 fixture가 같은 필수 field를 반환한다.",
        boundaryTest: "provider 실패 시 허용 여부에 따라 fallback 또는 구조화 오류가 난다.",
        serviceCase: "비용·보안·지연에 따라 로컬과 API 모델을 교체하는 회의 서비스",
        screenshot: ["ollama-langchain-provider-local.png", "https://ollama.com/library/qwen3"],
      }),
      P(15, "Action Item 근거 검증", {
        outcome: "모든 결정과 할 일을 원문 segment ID에 연결한다.",
        why: "담당자와 기한을 잘못 붙이면 회의 자동화가 오히려 조정 비용을 만든다.",
        artifact: "validated_meeting_brief.json",
        terms: [T("Evidence", "결과를 뒷받침하는 원문 구간"), T("Grounding", "출력 내용을 입력 근거에 묶는 것"), T("Hallucination", "원문에 없는 내용을 만든 오류"), T("Spot check", "위험 구간만 사람이 확인")],
        pipeline: ["결정 추출", "Action Item 추출", "evidence ID 연결", "미상값 null", "사람 승인"],
        files: ["src/meeting_agent_workflow.py", "src/course_services/meeting_service.py", "tests/test_meeting_agent_workflow.py", "output/day1-meeting-agent-ollama/workflow_result.json"],
        command: "python -m src.meeting_agent_workflow --help",
        failure: "evidence ID가 존재하지만 실제 문장과 의미가 맞지 않는다.",
        recovery: "구조 검사는 code evaluator, 의미 검사는 표본 human review로 나눈다.",
        codex: "Action Item evidence 누락·unknown ID를 각각 재현하는 test를 추가한다.",
        normalTest: "모든 evidence ID가 known segment에 존재한다.",
        boundaryTest: "없는 s99를 가리키면 ACTION_n_UNKNOWN_EVIDENCE다.",
        serviceCase: "회의 후 담당 업무를 자동 제안하되 게시 전 원문 근거를 확인",
        screenshot: ["langgraph-interrupt-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"],
      }),
      P(16, "도메인별 Golden Set", {
        outcome: "이커머스·교육·금융 사례에 맞는 평가 case를 만든다.",
        why: "범용 요약 점수만으로는 금액·날짜·상품명 같은 도메인 오류를 잡지 못한다.",
        artifact: "day2_eval_cases.json",
        terms: [T("Golden case", "팀이 합의한 대표 입력과 기대 결과"), T("Evaluator", "결과를 검사하는 함수"), T("Regression", "변경 후 이전 동작이 깨진 상태"), T("Release gate", "배포 여부를 가르는 기준")],
        pipeline: ["실패 사례 수집", "비식별", "expected field 작성", "baseline 실행", "Day 2 tag"],
        files: ["data/meeting_sample_ko_12min_expected.json", "src/observability_lab.py", "tests/test_observability_workflow.py", "materials/day2/day2_service_lab.ipynb"],
        command: "python -m pytest -q tests/test_meeting_agent_workflow.py tests/test_observability_workflow.py",
        failure: "데모 한 건 성공을 서비스 전체 품질로 일반화한다.",
        recovery: "숫자·이름·기한·무음·반복을 포함한 작은 golden set부터 운영한다.",
        codex: "대표 실패를 재현하는 test를 먼저 쓰고 최소 변경으로 통과시킨다.",
        normalTest: "합성 회의 정상 case가 READY_FOR_EXPORT다.",
        boundaryTest: "STT HOLD나 사람 거절은 최종 READY가 될 수 없다.",
        serviceCase: "현업에서는 상담/회의 유형별 scorecard, 포트폴리오에는 실패 사례 3건",
        screenshot: ["langsmith-evaluation-official.png", "https://docs.langchain.com/langsmith/evaluation"],
      }),
    ],
  },
  3: {
    deckTitle: "Day 3 · 코드 리뷰 Agent",
    subtitle: "변경 라인 · Test 근거 · 리뷰 평가",
    service: "Review Intelligence Service",
    periods: [
      P(17, "코드 리뷰 기준과 Severity", {
        outcome: "P0~P3 severity와 actionable finding 기준을 합의한다.", why: "스타일 지적이 많아질수록 중요한 correctness 오류가 묻힌다.", artifact: "review_rubric.md",
        terms: [T("Finding", "한 가지 문제와 교정 제안"), T("Severity", "사용자 영향과 긴급도"), T("False positive", "문제가 아닌데 문제라고 한 결과"), T("Confidence", "근거에 대한 확신 정도")],
        pipeline: ["변경 확인", "사용자 영향", "재현 조건", "근거 라인", "가장 작은 교정"], files: ["AGENTS.md", "src/course_services/contracts.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day3/day3_service_lab.ipynb"],
        command: "python -m pytest -q tests/test_course_services.py -k maps_findings", failure: "모든 의견을 P1으로 부풀려 개발자가 경고를 무시한다.", recovery: "correctness·security·data loss·contract break에 집중하고 style은 linter에 맡긴다.", codex: "AGENTS.md 리뷰 기준을 읽고 바뀐 라인에만 finding을 작성하게 한다.", normalTest: "한 finding에는 path·line·severity·근거·제안이 모두 있다.", boundaryTest: "변경과 무관한 파일 의견은 게시 후보에서 제외한다.", serviceCase: "작은 팀의 PR 대기 시간을 줄이는 첫 번째 자동 검토",
        screenshot: ["codex-cli-official.png", "https://developers.openai.com/codex/cli"],
      }),
      P(18, "Unified Diff와 Line Mapping", {
        outcome: "hunk header로 새 파일 line number를 복원한다.", why: "내용이 맞아도 line mapping이 틀리면 GitHub comment는 422 또는 엉뚱한 위치에 붙는다.", artifact: "parsed_hunks.json",
        terms: [T("Diff", "변경 전후 차이"), T("Hunk", "연속된 변경 구간"), T("Old line", "변경 전 파일의 줄"), T("New line", "변경 후 파일의 줄")], pipeline: ["+++ target 확인", "@@ header parse", "context는 양쪽 증가", "삭제는 old만 증가", "추가는 new에 기록"], files: ["src/course_services/review_service.py", "tests/test_course_services.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day3/day3_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k unified_diff", failure: "파일 header와 코드의 + 기호를 같은 것으로 처리한다.", recovery: "+++ header를 먼저 분리하고 hunk 안의 추가 라인만 수집한다.", codex: "rename·new file·삭제 only diff를 포함한 parser boundary test를 제안받는다.", normalTest: "추가된 9·11·12번 줄에 finding이 매핑된다.", boundaryTest: "absolute path와 hunk 없는 입력은 구조화 실패다.", serviceCase: "GitHub·GitLab에서 공통으로 쓰는 diff 분석 core",
        screenshot: ["github-repository-quickstart-official.png", "https://docs.github.com/repositories/creating-and-managing-repositories/quickstart-for-repositories"],
      }),
      P(19, "리뷰 Context Pack", {
        outcome: "변경 파일·직접 호출부·관련 test만 context pack으로 고른다.", why: "파일을 많이 넣으면 정확도가 자동으로 오르는 대신 비용과 상충 정보가 늘어난다.", artifact: "context_pack.json",
        terms: [T("Repo context", "변경을 이해하는 데 필요한 저장소 정보"), T("Dependency", "변경 코드가 의존하는 대상"), T("Call site", "함수를 실제 호출하는 위치"), T("Context budget", "한 번에 전달할 문맥 한도")], pipeline: ["changed path", "관련 symbol", "가까운 test", "정책 문서", "불필요 문맥 제외"], files: ["AGENTS.md", "src/course_services/review_service.py", "tests/test_course_services.py", "README.md"], command: "rg -n \"run_review_service|ReviewFinding\" src tests", failure: "비밀키·대용량 로그·무관한 output까지 context에 넣는다.", recovery: "rg로 후보를 좁히고 secret·generated output을 명시적으로 제외한다.", codex: "저장소를 이해하되 수정 전 관련 파일과 test를 먼저 나열하게 한다.", normalTest: "context pack에 changed_paths와 test_candidates가 남는다.", boundaryTest: "workspace 밖·.env·실행 cache는 context에서 제외한다.", serviceCase: "수천 파일 monorepo에서 리뷰 latency와 비용을 줄이는 selection",
        screenshot: ["vscode-repo-workspace-local.png", "https://code.visualstudio.com/docs/editor/workspaces"],
      }),
      P(20, "ReviewFinding 결과 계약", {
        outcome: "ReviewFinding과 ReviewReport를 Pydantic으로 검증한다.", why: "자유 문장은 deduplication·line comment·평가에 다시 쓰기 어렵다.", artifact: "review_report.json",
        terms: [T("Contract", "호출자와 구현 사이의 약속"), T("extra=forbid", "모르는 필드를 거부"), T("Error code", "복구 판단에 쓰는 이름"), T("Automatic publish", "사람 없이 게시되는 동작")], pipeline: ["finding validate", "line mapping", "report aggregate", "automatic_publish false", "expected failure code"], files: ["src/course_services/contracts.py", "src/course_services/review_service.py", "tests/test_course_services.py", "data/day5_eval/golden_review_findings.json"], command: "python -m pytest -q tests/test_course_services.py", failure: "schema 오류가 raw traceback으로 notebook을 끝낸다.", recovery: "EXPECTED_FAILURE와 error_code로 바꾸고 원인은 trace에 남긴다.", codex: "contract 변경 시 정상·누락 field·extra field test를 함께 갱신한다.", normalTest: "confidence 0~1과 line>=1이 검증된다.", boundaryTest: "automatic_publish=true는 model validation에서 차단된다.", serviceCase: "리뷰 결과를 IDE·PR·대시보드에서 같은 형식으로 재사용",
        screenshot: ["pytest-getting-started-official.png", "https://docs.pytest.org/en/stable/getting-started.html"],
      }),
      P(21, "Prompt Baseline과 의도적 Bug", {
        outcome: "의도적 bug diff에서 baseline finding을 만든다.", why: "실제 PR만으로 튜닝하면 무엇이 개선됐는지 비교할 정답이 없다.", artifact: "baseline_review.json",
        terms: [T("Baseline", "개선 전 비교 기준"), T("Few-shot", "입출력 예시를 prompt에 제공"), T("Rule ID", "같은 오류 유형을 묶는 식별자"), T("Deterministic", "같은 입력에 재현 가능한 결과")], pipeline: ["synthetic diff", "rule baseline", "LLM candidate", "schema validate", "사람 비교"], files: ["data/day3_review_cases/unsafe_pr.diff", "src/course_services/review_service.py", "materials/day3/day3_service_lab.ipynb", "output/day3-review/baseline.json"], command: "python -m pytest -q tests/test_course_services.py -k maps_findings", failure: "LLM이 존재하지 않는 runtime 결과를 근거로 finding을 만든다.", recovery: "diff·static check·실제 test output만 evidence로 허용한다.", codex: "baseline rule 하나를 구현하고 test가 먼저 실패하는지 확인한 뒤 수정한다.", normalTest: "eval·외부 쓰기·broad except 세 finding이 나온다.", boundaryTest: "빈 diff는 그럴듯한 빈 성공이 아니라 EMPTY_DIFF다.", serviceCase: "교육용 bug repo에서 reviewer의 품질 변화 설명",
        screenshot: ["vscode-pytest-19-passed-local.png", "https://code.visualstudio.com/docs/python/testing"],
      }),
      P(22, "정적 분석·LLM Hybrid Review", {
        outcome: "ruff·pytest 결과와 의미 리뷰를 한 context로 합친다.", why: "문법·unused import까지 LLM에 맡기면 느리고 일관성도 낮다.", artifact: "hybrid_review.json",
        terms: [T("Static analysis", "코드를 실행하지 않고 규칙으로 검사"), T("Unit test", "작은 기능의 동작을 검증"), T("Hybrid review", "결정론 검사와 의미 검토 결합"), T("Evidence", "실제 명령과 변경 라인")], pipeline: ["ruff", "focused pytest", "diff parse", "LLM review", "deduplicate"], files: ["AGENTS.md", "tests/test_course_services.py", "src/course_services/review_service.py", ".github/workflows/test.yml"], command: "python -m pytest -q tests/test_course_services.py", failure: "실행하지 않은 test를 passed라고 prompt에 써 둔다.", recovery: "command·exit code·stdout 요약을 실행 후 evidence bundle에 넣는다.", codex: "코드를 만든 뒤 focused test와 full suite를 실제로 실행하고 결과를 보고하게 한다.", normalTest: "결정론 finding과 test evidence가 같은 report에 존재한다.", boundaryTest: "test 미실행은 READY_FOR_HUMAN_MERGE가 아니다.", serviceCase: "PR이 열리면 자동 검사 후 개발자가 고위험 finding만 검토",
        screenshot: ["vscode-pytest-25-passed-local.png", "https://code.visualstudio.com/docs/python/testing"],
      }),
      P(23, "Precision·Recall 기반 평가", {
        outcome: "golden finding과 predicted finding을 exact key로 비교한다.", why: "많이 지적하는 reviewer가 실제로 더 좋은 reviewer라는 보장은 없다.", artifact: "review_eval.json",
        terms: [T("Precision", "제기한 문제 중 맞은 비율"), T("Recall", "잡아야 할 문제 중 찾은 비율"), T("F1", "precision과 recall의 조화 평균"), T("Golden set", "합의된 기대 finding 모음")], pipeline: ["key 정규화", "교집합", "false positive", "false negative", "release gate"], files: ["src/course_services/eval_service.py", "data/day5_eval/golden_review_findings.json", "tests/test_course_services.py", "materials/day3/day3_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k offline_eval", failure: "제목 문구가 조금 달라졌다고 같은 finding을 다른 것으로 센다.", recovery: "path·line·rule_id 같은 안정 key를 평가에 사용한다.", codex: "평가 함수를 구현할 때 empty prediction·empty expected 경계를 test한다.", normalTest: "fixture case precision·recall·F1이 1.0이다.", boundaryTest: "recall 또는 precision 0.8 미만이면 HOLD다.", serviceCase: "모델 교체 전 기존 reviewer보다 나아졌는지 정량 비교",
        screenshot: ["langsmith-evaluation-official.png", "https://docs.langchain.com/langsmith/evaluation"],
      }),
      P(24, "오류 분석과 회귀 방지", {
        outcome: "false positive·false negative 원인을 분류하고 Day 3 report를 만든다.", why: "평균 점수만 보면 특정 언어·파일·위험 유형의 반복 실패가 보이지 않는다.", artifact: "day3_review_report.md",
        terms: [T("Error analysis", "틀린 결과의 패턴을 분류"), T("Regression", "이전보다 나빠진 동작"), T("Ablation", "구성요소를 빼 영향 확인"), T("Human merge", "최종 반영은 사람이 결정")], pipeline: ["실패 목록", "원인 label", "최소 수정", "회귀 test", "commit·tag"], files: ["src/course_services/codex_harness.py", "tests/test_course_services.py", "AGENTS.md", "materials/day3/day3_service_lab.ipynb"], command: "git diff -- src/course_services tests/test_course_services.py", failure: "점수를 올리려고 기존 assertion이나 policy를 약화한다.", recovery: "실패를 대표 test로 추가하고 최소 변경만 허용한다.", codex: "diff를 검토하고 actionable finding만 보고한 뒤 test 증거를 다시 확인한다.", normalTest: "허용된 path·focused test·diff review가 모두 충족된다.", boundaryTest: ".env 변경·secret 탐지·미실행 test 중 하나라도 있으면 HOLD다.", serviceCase: "현업은 merge 보조, 구직자는 리뷰 품질 리포트와 회귀 test를 포트폴리오로 제출",
        screenshot: ["codex-cli-docs-official.png", "https://developers.openai.com/codex/cli"],
      }),
    ],
  },
  4: {
    deckTitle: "Day 4 · GitHub PR 자동화",
    subtitle: "PR 수집 · LangGraph 승인 · 안전한 게시",
    service: "PR Review Automation Service",
    periods: [
      P(25, "PR 자동화는 target을 정확히 읽는 것부터 시작합니다", { outcome: "repository·PR number·head SHA·diff를 fixture에서 읽는다.", why: "대상 commit이 바뀌면 이전 line mapping과 review comment가 stale해진다.", artifact: "pr_target.json", terms: [T("PR", "변경을 검토·병합하는 요청"), T("Commit", "특정 시점의 변경 묶음"), T("Head SHA", "PR 최신 commit 식별자"), T("Review comment", "diff line에 붙는 의견")], pipeline: ["fixture load", "target validate", "head SHA 고정", "diff load", "read-only result"], files: ["data/day4_github/pr_fixture.json", "src/course_services/github_service.py", "data/day3_review_cases/unsafe_pr.diff", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k github", failure: "화면에 보이는 PR 제목만 믿고 repo·number·SHA를 확인하지 않는다.", recovery: "쓰기 전 target 세 필드를 payload와 승인 화면에 다시 표시한다.", codex: "fixture loader에 필수 field·workspace path test를 추가한다.", normalTest: "synthetic fixture가 PullRequestTarget으로 validate된다.", boundaryTest: "필드 누락이나 workspace 밖 fixture는 구조화 오류다.", serviceCase: "사내 repo PR을 읽어 검토 대기열을 만드는 read-only bot", screenshot: ["github-repository-quickstart-official.png", "https://docs.github.com/repositories/creating-and-managing-repositories/quickstart-for-repositories"] }),
      P(26, "토큰은 기능이 아니라 권한과 만료를 가진 비밀입니다", { outcome: "fine-grained token과 최소 repository permission을 설명한다.", why: "교육용 token 하나가 실수로 commit되면 저장소 전체 위험으로 번진다.", artifact: ".env.sample", terms: [T("PAT", "개인 API 접근 토큰"), T("Fine-grained", "대상과 권한을 좁힌 token"), T("Secret", "소스·로그에 남기면 안 되는 값"), T("Least privilege", "필요한 최소 권한만 부여")], pipeline: ["권한 목록", "sandbox repo", ".env local", ".gitignore", "만료·폐기"], files: [".env.sample", ".gitignore", "AGENTS.md", "data/day4_github/pr_fixture.json"], command: "git check-ignore -v .env", failure: "token 값을 notebook output이나 screenshot에 노출한다.", recovery: "존재 여부만 bool로 확인하고 노출된 token은 즉시 폐기·재발급한다.", codex: "secret을 읽거나 출력하지 않는 범위에서 config validation만 구현한다.", normalTest: ".env는 ignore되고 .env.sample만 추적된다.", boundaryTest: "token이 없으면 401을 재시도하지 않고 실행을 중단한다.", serviceCase: "교육에서는 mock, 운영에서는 App token·short-lived credential 고려", screenshot: ["github-rest-auth-official.png", "https://docs.github.com/rest/authentication/authenticating-to-the-rest-api"] }),
      P(27, "REST client는 status code를 복구 결정으로 바꿔야 합니다", { outcome: "read-only PR 조회와 pagination·rate limit 계약을 만든다.", why: "모든 오류를 같은 retry로 처리하면 인증 문제와 rate limit이 장애를 키운다.", artifact: "github_read_result.json", terms: [T("REST", "HTTP resource 단위 API 방식"), T("Pagination", "여러 페이지로 결과를 나눔"), T("Rate limit", "시간당 요청 제한"), T("Retry-After", "다시 요청 가능한 시각 힌트")], pipeline: ["GET request", "status classify", "pagination", "bounded backoff", "structured result"], files: ["src/course_services/github_service.py", "materials/day4/day4_service_lab.ipynb", "AGENTS.md", "output/day4-github/read-result.json"], command: "python -m pytest -q tests/test_course_services.py", failure: "401·403·404·422·429를 모두 세 번 retry한다.", recovery: "재인증·권한 확인·target 확인·diff 갱신·대기 경로를 error code별로 나눈다.", codex: "fake HTTP response로 각 status code의 결정론 test를 작성한다.", normalTest: "200 응답은 target·diff·rate metadata를 반환한다.", boundaryTest: "429만 Retry-After와 최대 횟수 안에서 재시도한다.", serviceCase: "PR 정보를 안전하게 수집하는 ingestion adapter", screenshot: ["git-first-setup-official.png", "https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup"] }),
      P(28, "LangGraph state에는 다음 결정을 위한 값만 둡니다", { outcome: "PR review의 node·edge·conditional edge를 조립한다.", why: "모든 원문과 client 객체를 state에 넣으면 checkpoint와 재시작이 불안정해진다.", artifact: "compiled_review_graph", terms: [T("State", "node 사이에 전달할 명시 데이터"), T("Node", "한 책임을 실행하는 함수"), T("Edge", "다음 실행 순서"), T("Conditional edge", "상태에 따른 분기")], pipeline: ["validate target", "load diff", "review", "human review", "dry-run"], files: ["src/langgraph_lab.py", "src/meeting_agent_workflow.py", "src/course_services/github_service.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "state에 token·client·raw audio를 넣어 checkpoint에 남긴다.", recovery: "ID·status·검증 결과만 state에 두고 외부 자원은 adapter 경계에서 주입한다.", codex: "기존 service 함수를 node로 감싸되 contract를 바꾸지 않게 한다.", normalTest: "approve·edit·reject가 서로 다른 terminal state로 간다.", boundaryTest: "validation error는 publish node에 도달하지 않는다.", serviceCase: "회의 Agent와 PR Agent가 같은 승인 패턴을 재사용", screenshot: ["langgraph-overview-official.png", "https://docs.langchain.com/oss/python/langgraph/overview"] }),
      P(29, "재시작 가능한 workflow는 같은 일을 두 번 하지 않습니다", { outcome: "retry·checkpoint·request ID·idempotency를 연결한다.", why: "interrupt 전후 node가 다시 실행돼도 외부 쓰기는 한 번이어야 한다.", artifact: "checkpoint_and_audit.json", terms: [T("Checkpoint", "중단 시 state 저장"), T("Thread ID", "같은 실행을 이어 가는 식별자"), T("Idempotency", "같은 요청을 반복해도 결과가 한 번인 성질"), T("Backoff", "재시도 간격을 점차 늘림")], pipeline: ["request ID", "checkpoint", "bounded retry", "idempotency lookup", "reuse result"], files: ["src/course_services/github_service.py", "src/langgraph_lab.py", "tests/test_course_services.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k idempotent", failure: "timeout 뒤 동일 comment를 다시 게시한다.", recovery: "target·SHA·body hash를 idempotency key로 저장하고 기존 remote result를 재사용한다.", codex: "같은 plan을 두 번 실행해 publisher call이 1회인지 test한다.", normalTest: "첫 실행은 reused=false, 두 번째는 true다.", boundaryTest: "body나 head SHA가 달라지면 새 승인 대상으로 본다.", serviceCase: "네트워크가 불안한 CI bot의 중복 comment 방지", screenshot: ["langgraph-persistence-official.png", "https://docs.langchain.com/oss/python/langgraph/persistence"] }),
      P(30, "Human Approval은 버튼보다 검토할 정보가 중요합니다", { outcome: "approve·edit·reject interrupt payload를 설계한다.", why: "초안만 보여주고 대상과 근거를 숨기면 사람은 사실상 승인할 수 없다.", artifact: "review_decision.json", terms: [T("Interrupt", "workflow를 멈추고 입력을 기다림"), T("Approve", "초안을 그대로 허용"), T("Edit", "사람이 수정 후 허용"), T("Reject", "외부 쓰기 없이 종료")], pipeline: ["초안 생성", "target 표시", "finding 근거", "사람 결정", "같은 thread resume"], files: ["src/langgraph_lab.py", "src/meeting_agent_workflow.py", "web-demo/app.js", "materials/day4/day4_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "interrupt를 일반 Exception으로 잡아 자동 진행한다.", recovery: "interrupt를 workflow event로 두고 같은 thread_id와 JSON decision으로 resume한다.", codex: "승인 node 전에 외부 쓰기 호출이 존재하지 않는지 diff review한다.", normalTest: "approve가 READY_FOR_EXPORT로 간다.", boundaryTest: "reject는 external_write=false와 REJECTED로 끝난다.", serviceCase: "PR comment·메일·ticket 생성 전에 동일 승인 UI 사용", screenshot: ["langgraph-interrupts-official.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(31, "Dry-run은 실제 게시 직전의 완성된 결과여야 합니다", { outcome: "PR comment body·target·idempotency key를 local JSON으로 만든다.", why: "대충 만든 preview는 실제 API payload와 달라 승인 증거가 되지 못한다.", artifact: "review_comment_plan.json", terms: [T("Dry-run", "외부 쓰기 없이 동일 payload 생성"), T("Payload", "API에 보낼 구조화 데이터"), T("Audit", "누가 무엇을 승인했는지 기록"), T("External write", "외부 시스템 상태를 바꾸는 호출")], pipeline: ["report validate", "comment render", "target bind", "hash key", "READY_FOR_APPROVAL"], files: ["src/course_services/github_service.py", "src/course_services/contracts.py", "tests/test_course_services.py", "materials/day4/day4_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k dry_run", failure: "dry_run=true인데 publisher가 호출된다.", recovery: "DRY_RUN_CANNOT_PUBLISH를 contract로 고정하고 fake publisher call 수를 assert한다.", codex: "dry-run 경계를 건드리는 변경에는 boundary test 없이는 완료하지 않는다.", normalTest: "payload에 repo·PR·SHA·body·key가 있다.", boundaryTest: "dry-run plan은 approval=true여도 publish되지 않는다.", serviceCase: "운영자가 Slack/PR 화면에서 실제 게시 내용을 사전 검토", screenshot: ["langgraph-reject-result-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(32, "실제 GitHub 쓰기는 본인 sandbox에서 한 건만 실행합니다", { outcome: "선택적으로 승인된 comment 한 건을 게시하고 audit ID를 남긴다.", why: "교육 실습이 타인 저장소나 업무 repo를 오염시키면 안 된다.", artifact: "day4_audit_record.json", terms: [T("Sandbox repo", "실습 전용 본인 저장소"), T("Publisher", "외부 API write adapter"), T("Remote ID", "게시 결과 식별자"), T("Rollback", "comment 삭제 또는 commit revert")], pipeline: ["sandbox 확인", "dry-run 검토", "사람 승인", "1회 POST", "response ID 기록"], files: ["materials/day4/day4_service_lab.ipynb", "src/course_services/github_service.py", ".env.sample", "AGENTS.md"], command: "python -m pytest -q tests/test_course_services.py", failure: "교육 코드에 live publisher와 token scope를 기본 포함한다.", recovery: "repo에는 fake publisher만 두고 live adapter는 강사 승인 후 별도 branch에서 연결한다.", codex: "PR 생성·리뷰·test 수정은 돕되 merge와 외부 게시 결정은 사람에게 남긴다.", normalTest: "fake publisher가 한 번 호출되고 remote ID가 audit에 남는다.", boundaryTest: "publisher 미설정·승인 없음·dry-run은 모두 BLOCKED다.", serviceCase: "현업은 GitHub App과 protected branch, 구직자는 sandbox demo recording", screenshot: ["codex-cli-official.png", "https://learn.chatgpt.com/use-cases"] }),
    ],
  },
  5: {
    deckTitle: "Day 5 · 통합·관측·평가·배포",
    subtitle: "서비스 통합 · LangSmith 관측 · 평가 · 배포",
    service: "Agent Operations Console",
    periods: [
      P(33, "Router는 파일 확장자가 아니라 명시된 업무 의도로 분기합니다", { outcome: "meeting_transcript와 code_diff를 같은 entry point에서 실행한다.", why: "모델 추측으로 업무 종류를 고르면 잘못된 tool과 권한이 연결될 수 있다.", artifact: "unified_service_result.json", terms: [T("Router", "입력을 알맞은 workflow로 전달"), T("Input kind", "호출자가 명시한 업무 종류"), T("Adapter", "서로 다른 service 결과를 연결"), T("Boundary", "읽기·쓰기·승인 경계")], pipeline: ["path validate", "input kind 확인", "meeting 또는 review", "공통 result", "사람 승인"], files: ["src/course_services/service_router.py", "src/course_services/meeting_service.py", "src/course_services/review_service.py", "materials/day5/day5_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k router", failure: "내용을 LLM에게 보여주고 업무 종류와 권한을 함께 추측시킨다.", recovery: "input_kind를 API contract로 받고 unsupported type은 거부한다.", codex: "새 service route를 추가할 때 workspace 경계와 external_write=false를 test한다.", normalTest: "회의와 diff가 각각 올바른 service 이름으로 반환된다.", boundaryTest: "unknown kind와 workspace escape는 EXPECTED_FAILURE다.", serviceCase: "한 화면에서 회의·PR 리뷰를 선택 실행하는 내부 도구", screenshot: ["langchain-langgraph-workflow-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/overview"] }),
      P(34, "LangSmith trace는 실행 과정을 질문할 수 있게 만듭니다", { outcome: "project·trace·run·thread의 관계를 이해하고 첫 trace를 남긴다.", why: "최종 JSON만 저장하면 느린 node와 실패 원인을 다시 찾기 어렵다.", artifact: "trace.json 또는 LangSmith run", terms: [T("Project", "관련 실행을 모으는 공간"), T("Trace", "한 요청의 전체 실행 계보"), T("Run", "node·LLM·tool 한 번의 실행"), T("Thread", "대화·재개 실행의 연속성")], pipeline: ["request start", "span 시작", "입력 최소화", "status·latency", "trace close"], files: ["src/observability_lab.py", "src/workflow_service.py", "output/day1-workflow/trace.json", ".env.sample"], command: "python -m src.workflow_service --decision approve --out output/day5-trace", failure: "raw transcript·token·고객 정보를 trace input에 그대로 보낸다.", recovery: "local trace 기본, synthetic/deidentified만 명시 upload, raw content는 제외한다.", codex: "새 node에 latency·status metadata를 추가하되 PII payload를 넣지 않는다.", normalTest: "trace에 span 계층과 READY/HOLD 결정이 남는다.", boundaryTest: "local_only나 key 없음은 upload하지 않고 error code를 반환한다.", serviceCase: "장애 문의에서 request ID로 어느 node가 실패했는지 조회", screenshot: ["langsmith-observability-official.png", "https://docs.langchain.com/langsmith/observability"] }),
      P(35, "운영 dashboard는 예쁜 그래프보다 결정 가능한 신호가 먼저입니다", { outcome: "status·error·latency·provider·cost metadata를 비교한다.", why: "평균 latency 하나만 보면 특정 provider와 실패 유형의 꼬리가 숨겨진다.", artifact: "monitoring_view.md", terms: [T("Tag", "실행을 분류하는 짧은 label"), T("Metadata", "조회·비교용 구조화 값"), T("Latency", "요청부터 결과까지 걸린 시간"), T("Cost", "token·compute 사용 비용")], pipeline: ["tag version", "provider metadata", "node latency", "error code", "READY/HOLD filter"], files: ["src/observability_lab.py", "output/day1-workflow/trace.json", "materials/day5/day5_service_lab.ipynb", "AGENTS.md"], command: "python -m pytest -q tests/test_observability_workflow.py", failure: "성공 trace만 보고 HOLD·reject·fallback을 제외한다.", recovery: "status와 fallback_reason을 같은 dashboard filter에 포함한다.", codex: "추적 field를 늘리기 전에 운영 질문 한 개와 필요한 metadata만 정의한다.", normalTest: "provider_used와 node latency를 필터링할 수 있다.", boundaryTest: "오류 원문 대신 stable error_code와 type만 외부 trace에 남는다.", serviceCase: "모델 교체 후 latency·fallback·HOLD 비율 비교", screenshot: ["langsmith-pricing-official.png", "https://www.langchain.com/pricing"] }),
      P(36, "평가는 같은 dataset으로 baseline과 candidate를 비교해야 합니다", { outcome: "golden review case를 code evaluator로 실행한다.", why: "데모 입력이 매번 달라지면 개선인지 운인지 구분할 수 없다.", artifact: "experiment_result.json", terms: [T("Dataset", "반복 평가할 입력·정답 묶음"), T("Experiment", "특정 버전을 dataset에 실행"), T("Code evaluator", "규칙으로 자동 채점"), T("Candidate", "새로 비교할 구현")], pipeline: ["golden load", "baseline run", "candidate run", "metric compare", "release gate"], files: ["src/course_services/eval_service.py", "data/day5_eval/golden_review_findings.json", "tests/test_course_services.py", "materials/day5/day5_service_lab.ipynb"], command: "python -m pytest -q tests/test_course_services.py -k offline_eval", failure: "LLM judge 한 개 점수를 객관적 정답처럼 사용한다.", recovery: "schema·line mapping·policy는 code evaluator, 의미 품질은 human sample로 나눈다.", codex: "새 평가 지표에 empty set과 threshold boundary test를 추가한다.", normalTest: "fixture precision·recall·F1이 1.0이다.", boundaryTest: "precision 또는 recall 0.8 미만은 HOLD다.", serviceCase: "릴리스 후보가 기존 version보다 실제로 나아졌는지 비교", screenshot: ["langsmith-evaluation-official.png", "https://docs.langchain.com/langsmith/evaluation"] }),
      P(37, "사람 피드백은 좋아요 버튼보다 판단 이유가 필요합니다", { outcome: "approve·edit·reject와 수정 이유를 label로 남긴다.", why: "단순 thumbs-up은 어떤 오류를 고쳐야 하는지 알려주지 못한다.", artifact: "human_feedback.jsonl", terms: [T("Annotation", "사람이 결과에 붙인 label"), T("Feedback", "실행 품질에 대한 평가"), T("Queue", "검토가 필요한 실행 목록"), T("Reviewer agreement", "검토자 판단 일치 정도")], pipeline: ["HOLD sample", "근거 표시", "사람 결정", "reason label", "dataset 후보"], files: ["src/meeting_agent_workflow.py", "src/langgraph_lab.py", "web-demo/app.js", "materials/day5/day5_service_lab.ipynb"], command: "python -m src.langgraph_lab --decision all", failure: "사람 수정 내용을 곧바로 training data로 재사용한다.", recovery: "동의·비식별·품질 검토 후 별도 dataset 승인을 거친다.", codex: "feedback schema와 allowed label을 구현하고 unknown label을 차단한다.", normalTest: "approve·edit·reject가 reviewer·reason과 저장된다.", boundaryTest: "PII가 있는 raw content는 annotation export에서 제외된다.", serviceCase: "운영자 검토 결과를 다음 prompt·rule 개선 후보로 연결", screenshot: ["langgraph-interrupt-demo-local.png", "https://docs.langchain.com/oss/python/langgraph/interrupts"] }),
      P(38, "운영 가능한 Agent는 개인정보와 장애 대응을 먼저 설명합니다", { outcome: "redaction·retention·access·incident checklist를 만든다.", why: "회의·상담·코드에는 개인 정보와 회사 비밀이 동시에 들어갈 수 있다.", artifact: "ops_checklist.md", terms: [T("PII", "개인을 식별할 수 있는 정보"), T("Redaction", "민감 정보를 가리거나 제거"), T("Retention", "데이터 보관 기간"), T("Incident", "보안·품질 장애 사건")], pipeline: ["classify", "minimize", "redact", "retain/delete", "incident review"], files: ["src/observability_lab.py", "AGENTS.md", ".env.sample", "materials/day1/강사_회의음성_라이브데모_런북.md"], command: "python -m pytest -q tests/test_observability_workflow.py", failure: "편의를 위해 원본 audio와 raw prompt를 무기한 외부에 보관한다.", recovery: "목적·동의·최소수집·보존기한·삭제 경로를 배포 전 결정한다.", codex: "trace scrubber가 token·email·전화번호를 제거하는 정상·실패 test를 만든다.", normalTest: "synthetic·deidentified만 외부 upload 후보가 된다.", boundaryTest: "local_only와 secret 탐지는 upload를 차단한다.", serviceCase: "교육 데모에서 시작해 실제 고객 데이터로 넘어가기 위한 readiness gate", screenshot: ["google-meet-notes-official.png", "https://support.google.com/meet/answer/14754931"] }),
      P(39, "배포 후보는 코드·문서·demo가 같은 버전을 가리켜야 합니다", { outcome: "test·README·sample data·Vercel demo를 release candidate로 묶는다.", why: "코드는 최신인데 화면과 문서가 이전 schema면 사용자는 첫 실행에서 막힌다.", artifact: "release_candidate", terms: [T("Release candidate", "배포 직전 검증 버전"), T("Smoke test", "핵심 경로의 빠른 점검"), T("README", "설치·실행·복구 안내"), T("Demo", "실제 입력과 결과를 보여주는 시연")], pipeline: ["focused tests", "full suite", "README", "demo build", "human release"], files: ["README.md", "web-demo/", "scripts/run_day1_preflight.py", "materials/day5/day5_service_lab.ipynb"], command: "python scripts/run_day1_preflight.py", failure: "Vercel 화면만 동작하고 backend result contract와 다른 mock을 보여준다.", recovery: "Python output JSON을 demo의 단일 input으로 사용하고 schema version을 표시한다.", codex: "기능 구현 후 README·test·demo data가 같은 contract인지 diff로 검토한다.", normalTest: "local fixture로 end-to-end 결과와 demo JSON이 생성된다.", boundaryTest: "build 실패·test 실패·HOLD가 있으면 release candidate가 아니다.", serviceCase: "내부 시연 URL과 재현 가능한 GitHub repo를 한 번에 전달", screenshot: ["langchain-langgraph-workflow-demo-local.png", "https://vercel.com/docs"] }),
      P(40, "최종 발표는 모델 자랑보다 문제·증거·운영 결정을 보여줍니다", { outcome: "3분 demo와 2분 질문으로 서비스 가치를 검증한다.", why: "기능 목록만 보여주면 왜 안전하고 운영 가능한지 판단할 수 없다.", artifact: "final_tag_and_scorecard", terms: [T("Problem", "누구의 어떤 반복 업무인지"), T("Evidence", "실행·test·평가 결과"), T("Trade-off", "선택으로 얻고 포기한 것"), T("Next step", "다음 검증 우선순위")], pipeline: ["문제 30초", "live demo 90초", "실패·HITL 30초", "평가 30초", "질문 2분"], files: ["README.md", "materials/day5/day5_service_lab.ipynb", "output/day1-workflow/", "slides/"], command: "git status --short && python -m pytest -q", failure: "성공 화면만 보여주고 실패·사람 승인·평가를 생략한다.", recovery: "정상 한 건과 대표 HOLD 한 건을 나란히 보여준다.", codex: "발표 전 저장소 구조·README·test 증거를 다시 점검하고 누락만 보완한다.", normalTest: "처음 보는 사람이 repo에서 demo를 재현할 수 있다.", boundaryTest: "비밀키·실제 고객 데이터·자동 외부 쓰기는 발표 자료에 없다.", serviceCase: "재직자는 업무 적용 계획, 구직자는 제품 판단과 검증 능력을 포트폴리오로 제시", screenshot: ["codex-cli-docs-official.png", "https://learn.chatgpt.com/use-cases"] }),
    ],
  },
};

export const DAY_TIMES = [
  ["09:00-09:50", "1차시"],
  ["09:50-10:40", "2차시"],
  ["10:40-11:30", "3차시"],
  ["12:00-12:50", "4차시"],
  ["12:50-13:40", "5차시"],
  ["15:00-15:50", "6차시"],
  ["15:50-16:40", "7차시"],
  ["16:40-17:30", "8차시"],
];

export const CODEX_OFFICIAL_SOURCE = "https://learn.chatgpt.com/use-cases";
export const OPENAI_CODEX_DOCS = "https://developers.openai.com/codex/";
export const CLAUDE_CODE_DESKTOP = "https://code.claude.com/docs/en/desktop";
export const CLAUDE_CODE_QUICKSTART = "https://code.claude.com/docs/en/desktop-quickstart";
